/**
 * The desk-stage contract: THE TEST THAT CROSSES THE REPO BOUNDARY.
 *
 * THE INCIDENT (adversary kill, 2026-08-22). The CEO's desk counter lives in
 * ClarkHarness (`app/fund/desk.py`) and the CEO's desk page lives here. The
 * repair that made the spine the single definition of "whose move is it" was
 * shipped with a defect of exactly the shape it was fixing: a row at status
 * `accepted` carrying `next_actor: "ceo"` — the constitution's preserved COO
 * objection, verbatim, "items at status `accepted` whose execution requires
 * the CEO personally (three live today, including PM R1, the largest-money
 * decision in the firm)" — counted as CEO load in Python and rendered as
 * "shown, never counted" here. Server 1, page 0, on the same line.
 *
 * **Both suites were green over it: 12/12 TypeScript, 70/70 pytest.** Each
 * pinned its own side; nothing in either crossed the boundary, so nothing
 * could disagree. Two green suites pinning opposite behaviours in two repos is
 * how that shipped, and this file is the only kind of test that could have
 * caught it.
 *
 * HOW IT CROSSES A BOUNDARY WITH NO SHARED BUILD:
 *
 *   `contract/desk_stage_contract.v1.json` is generated BY `desk.py` (never
 *   typed by hand, so it cannot encode a wish) and checked in to both repos,
 *   byte-identical. ClarkHarness asserts the file still describes its code.
 *   This file runs THIS repo's own functions over the same rows and asserts
 *   the same numbers. The digest is pinned in both places, so neither copy
 *   moves without a human touching a test.
 *
 * THE RESIDUAL HOLE, NAMED: ClarkHarness regenerating while this copy stays
 * stale is invisible to both hermetic suites. So `desk_load` publishes
 * `contract_digest` and the CEO page renders a warning when the live spine's
 * digest differs from `CONTRACT_DIGEST` below. The drift is caught against a
 * live spine, on screen, rather than not at all.
 *
 * Run: `node --experimental-strip-types --test src/app/clark/studio/desk/deskStageContract.test.ts`
 */

import { strict as assert } from "node:assert";
import { test } from "node:test";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

import {
  CONTRACT_DIGEST, contractDrift,
  orderItems, rankDeskItems, recItems, splitDeskItems, stageOfItem,
} from "./execDesk.ts";
import { officerDesk } from "./officerQueues.ts";

/**
 * THE DIGEST, PINNED IN SOURCE.
 *
 * Duplicated deliberately: `CONTRACT_DIGEST` in `execDesk.ts` is what the
 * PAGE compares the live spine against, and this literal is what the TEST
 * compares the file against. One constant serving both would let a single edit
 * move the page's expectation and its own check together, which is a lock with
 * the key taped to it.
 *
 * To change it: regenerate in ClarkHarness (`python scripts/gen_desk_contract.py`),
 * copy the file here, and update BOTH literals. Three deliberate acts.
 */
const PINNED_DIGEST =
  "c49516837a6a0033a65eae5be03a698d7c54a925827b3bab20f1a5f121d17fc2";

const CONTRACT_URL = new URL(
  "../../../../../contract/desk_stage_contract.v1.json", import.meta.url);

interface ContractCase {
  name: string;
  why: string;
  row: Record<string, unknown>;
  expect: {
    next_actor_resolved: string;
    next_actor_basis?: string;
    counted_for_ceo: boolean;
    stage?: string;
    on_the_desk_at_all?: boolean;
  };
}

interface Contract {
  contract: string;
  version: number;
  rules_version: string;
  covers: string;
  cases: ContractCase[];
  terminal_cases: ContractCase[];
  known_divergences: {
    id: string; case: string; who_is_right: string;
    direction_of_the_fix: string; live_rows_affected: number;
  }[];
  expect_totals: {
    desk_load_total: number;
    page_awaiting_total: number;
    known_divergence_count: number;
    by_actor: Record<string, number>;
    open_elsewhere: number;
    decided_awaiting_execution: number;
    explicit_next_actor: number;
  };
  digest: string;
}

function loadContract(): { body: Contract; raw: string } {
  let raw: string;
  try {
    raw = readFileSync(CONTRACT_URL, "utf8");
  } catch (e) {
    throw new Error(
      `the desk-stage contract is missing at ${CONTRACT_URL.pathname}. It is `
      + "generated in ClarkHarness by `python scripts/gen_desk_contract.py` "
      + "and copied here; without it this repo has no shared definition of "
      + `the CEO's desk count at all. (${(e as Error).message})`);
  }
  return { body: JSON.parse(raw) as Contract, raw };
}

/**
 * Python's `json.dumps(sort_keys=True, separators=(",", ":"),
 * ensure_ascii=False)`, reimplemented — because the digest must be computable
 * on both sides of the boundary or it proves nothing.
 *
 * Reimplemented rather than hashing the raw bytes on purpose: hashing bytes
 * would make the digest depend on indentation and line endings, and a
 * whitespace-only reformat in either repo would then read as a routing change.
 * Sorted-key canonicalisation is stable across both.
 */
function canonical(v: unknown): string {
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(canonical).join(",")}]`;
  const o = v as Record<string, unknown>;
  const keys = Object.keys(o).sort();
  return `{${keys.map((k) => `${JSON.stringify(k)}:${canonical(o[k])}`).join(",")}}`;
}

const run = (o: Record<string, unknown> = {}) =>
  ({ run_id: "contract", seat: "coo", task: "t",
     resolved_at: "2026-08-21T10:00:00+00:00", ...o }) as never;

/* ------------------------------------------------------------- the lock --- */

test("the contract file is the one this repo was written against", () => {
  /* If this fails, the copy here and the copy in ClarkHarness have drifted, or
   * somebody edited the fixture to make a failing assertion pass — which is
   * the only way a shared contract can be defeated from one side. */
  const { body } = loadContract();
  const withoutDigest = { ...body } as Record<string, unknown>;
  delete withoutDigest.digest;
  const computed = createHash("sha256")
    .update(canonical(withoutDigest), "utf8").digest("hex");

  assert.equal(computed, body.digest,
    "the contract's body no longer matches its own digest — the file has been "
    + "edited by hand. Regenerate it in ClarkHarness rather than patching it.");
  assert.equal(computed, PINNED_DIGEST,
    "the contract changed and this test was not updated. Regenerate in "
    + "ClarkHarness, copy the file here, and update PINNED_DIGEST *and* "
    + "CONTRACT_DIGEST in execDesk.ts — then read what actually changed.");
  assert.equal(CONTRACT_DIGEST, PINNED_DIGEST,
    "execDesk.ts's CONTRACT_DIGEST (what the PAGE compares the live spine "
    + "against) and this test's pin have diverged; the page would warn about a "
    + "healthy spine, or worse, stay quiet about a drifted one");
});

test("the canonical form agrees with Python's, or the digest proves nothing", () => {
  /* A cross-language digest is only a lock if both languages produce the same
   * bytes. This asserts the reimplementation above against a value Python
   * computed, on a value with the awkward parts: sorted keys out of order,
   * nested arrays, null, and non-ASCII (the contract is full of em-dashes and
   * curly quotes, and `ensure_ascii=False` leaves them raw). */
  assert.equal(
    canonical({ b: 1, a: [null, "—", { d: 2, c: "it's" }], A: true }),
    '{"A":true,"a":[null,"—",{"c":"it\'s","d":2}],"b":1}');
});

/* --------------------------------------------- the stage, case by case ---- */

test("every contract case reaches the stage the SPINE says it should", () => {
  const { body } = loadContract();
  assert.ok(body.cases.length >= 10, "the case table must not shrink quietly");
  for (const c of body.cases) {
    const items = recItems([c.row as never], [run()]);
    assert.equal(items.length, 1, `${c.name}: the row must survive recItems`);
    assert.equal(items[0].nextActor, c.expect.next_actor_resolved,
      `${c.name}: the item must carry the spine's resolved actor unchanged`);
    assert.equal(stageOfItem(items[0]), c.expect.stage,
      `${c.name}\n    WHY THIS CASE EXISTS: ${c.why}`);
    // The invariant restated per row: the counted stage IS the counted set.
    assert.equal(stageOfItem(items[0]) === "awaiting_decision",
      c.expect.counted_for_ceo,
      `${c.name}: this row's stage and the spine's count disagree`);
  }
});

test("terminal rows are dropped here, exactly as the spine drops them", () => {
  /* The second lock. `open_recommendations()` already excludes them; this
   * makes a widened feed unable to put a closed item back in front of the CEO
   * as though a click were owed on it. */
  const { body } = loadContract();
  assert.ok(body.terminal_cases.length >= 3);
  for (const c of body.terminal_cases) {
    assert.equal(c.expect.on_the_desk_at_all, false, "contract sanity");
    assert.deepEqual(recItems([c.row as never], [run()]), [],
      `${c.name}: a terminal row must never reach the desk`);
  }
});

/* ------------------------------------------------------- THE ONE NUMBER --- */

test("THE INVARIANT: the page's count equals the spine's, minus written exceptions", () => {
  /* This is the assertion the whole file exists for, and the one that could
   * have caught the kill. `desk_load(rows, [], []).total` in Python and
   * `officerDesk(...).awaitingTotal` here are the same question asked twice;
   * on 2026-08-22 they answered 11 and 6 for one payload, then — after the
   * repair — 1 and 0 for a single accepted row the CEO still owned. */
  const { body } = loadContract();
  const rows = body.cases.map((c) => c.row) as never[];
  const items = rankDeskItems(recItems(rows, [run()]));
  assert.equal(items.length, body.cases.length, "no row may vanish in recItems");

  const split = splitDeskItems(items);
  const desk = officerDesk({
    awaitingDecision: split.awaitingDecision,
    awaitingExecution: split.awaitingExecution,
    ownedElsewhere: split.ownedElsewhere,
    memos: [], asks: [],
  });

  const t = body.expect_totals;
  assert.equal(desk.awaitingTotal, t.page_awaiting_total,
    `the page counts ${desk.awaitingTotal}; the contract says it must count `
    + `${t.page_awaiting_total} (the spine's ${t.desk_load_total} less `
    + `${t.known_divergence_count} written exception(s))`);
  assert.equal(
    desk.awaitingTotal + t.known_divergence_count, t.desk_load_total,
    "the page and the spine disagree by more than the exceptions the contract "
    + "records. Either a new divergence has appeared — add it to "
    + "KNOWN_DIVERGENCES in ClarkHarness's gen_desk_contract.py, with its "
    + "owner, direction and live row count — or the repair regressed.");

  // The other two legs of the partition, so a fix that "balanced" the headline
  // by moving rows into the wrong bucket cannot pass.
  assert.equal(split.awaitingExecution.length, t.decided_awaiting_execution);
  assert.equal(split.ownedElsewhere.length, t.open_elsewhere);
  assert.equal(
    split.awaitingDecision.length + split.awaitingExecution.length
      + split.ownedElsewhere.length,
    body.cases.length, "the three stages must partition the rows");
});

test("each recorded divergence is REAL, here, right now", () => {
  /* An exception list is only honest if every entry is still true. A stale
   * entry silently widens the tolerance of the invariant above by one row —
   * which is exactly how a contract turns into permission. */
  const { body } = loadContract();
  for (const d of body.known_divergences) {
    const c = body.cases.find((x) => x.name === d.case);
    assert.ok(c, `divergence ${d.id}: names a case that is not in the contract`);
    const items = recItems([c!.row as never], [run()]);
    // The spine counts it...
    assert.equal(c!.expect.counted_for_ceo, true);
    assert.equal(stageOfItem(items[0]), "awaiting_decision");
    // ...and the page still does not, for the reason recorded.
    const desk = officerDesk({
      awaitingDecision: items, awaitingExecution: [], memos: [], asks: [],
    });
    assert.equal(desk.awaitingTotal, 0,
      `divergence ${d.id} is recorded as live but the page now counts this `
      + "row. If it was FIXED, remove the entry in ClarkHarness and "
      + "regenerate — a contract carrying a divergence that no longer exists "
      + "gives the invariant a row of slack for free.");
    // And the row is still SHOWN. "Do not solve a counting problem by hiding
    // work" — an uncounted row that also disappeared would be a worse defect
    // than the one being tolerated.
    assert.equal(desk.donna.notes.length, 1,
      `divergence ${d.id}: the uncounted row must still be on the page`);
  }
});

/* ---------------------------------- the two legs the contract does NOT cover */

test("orders and requests are one-to-one with the spine's other two legs", () => {
  /* Stated because the contract says so out loud: it covers the
   * `open_recommendations` leg only. `desk_load` adds `pending_orders` and
   * `requests_awaiting_approval`; those are asserted here rather than left to
   * "obviously fine", which is what was said about the recommendation leg.
   *
   *   pending orders — every row of `GET /fund/orders/pending` is a CEO click
   *     by construction (anything the auto-approval envelope took never
   *     appears there), so `orderItems` gives every one `nextActor: "ceo"`.
   *   requests — `desk_load` counts requests at status `open`; the page counts
   *     asks at stage `awaiting_ceo`, and `queuedAsks` maps open -> that stage
   *     and nothing else to it. */
  const { body } = loadContract();
  assert.match(body.covers, /open_recommendations leg/,
    "if the contract's scope changed, this test's premise changed with it");

  const orders = orderItems([
    { order_id: "o1", ts: "2026-08-22T00:00:00Z",
      impact_preview: { notional_usd: 750 } },
    { order_id: "o2", ts: "2026-08-22T00:00:01Z" },
  ] as never);
  for (const o of orders) {
    assert.equal(stageOfItem(o), "awaiting_decision",
      "a pending order is the CEO's click by construction");
  }
  const withOrders = officerDesk({
    awaitingDecision: orders, awaitingExecution: [], memos: [], asks: [],
  });
  assert.equal(withOrders.awaitingTotal, orders.length,
    "every pending order must reach the count exactly once");

  const asks = [
    { requestId: "r1", stage: "awaiting_ceo" },
    { requestId: "r2", stage: "cleared_to_trigger" },
    { requestId: "r3", stage: "declined" },
  ] as never[];
  const withAsks = officerDesk({
    awaitingDecision: [], awaitingExecution: [], memos: [], asks,
  });
  assert.equal(withAsks.awaitingTotal, 1,
    "only an ask AWAITING THE CEO is his; a cleared one is the chair's to "
    + "fire and a declined one is terminal, and `desk_load` counts requests at "
    + "status `open` for the same reason");
});

/* ------------------------------------------------- the live-drift warning -- */

test("the page can tell a drifted spine from an unverifiable one", () => {
  /* Three states, three renderings, because two of them are absences and this
   * fund has answered an unmeasurable with a confident answer four times. */
  assert.equal(contractDrift(PINNED_DIGEST), null, "agreement is silent");
  assert.equal(contractDrift(null), "unverified",
    "a spine that could not read its contract must not read as agreement");
  assert.equal(contractDrift(undefined), "unverified",
    "a spine predating the field is equally unverified, never agreeing");
  assert.equal(contractDrift("0".repeat(64)), "drifted",
    "a digest that differs is a real disagreement and must say so");
});
