"""Comprehensive financial profiles, segment models, and thematic dictionaries for equities."""

from __future__ import annotations

from typing import Any, Optional


COMPANY_PROFILES: dict[str, dict[str, Any]] = {
    "NVDA": {
        "name": "NVIDIA Corporation",
        "sector": "Semiconductors & AI Compute",
        "long_themes": [
            "Datacenter Compute & GPU Accelerators",
            "Blackwell Architecture Adoption & Packaging",
            "Sovereign AI & Global Infrastructure Demand",
            "Networking & NVLink System Expansion",
            "Hyperscaler Cloud Capex & Multi-Year Backlog",
        ],
        "short_themes": [
            "Customer Concentration & Hyperscaler Capex Digestion",
            "CoWoS Packaging & High-Bandwidth Memory Bottlenecks",
            "Geopolitical & Regional Export Licensing Restrictions",
            "Custom ASIC Competition from Cloud Hyperscalers",
            "Valuation Multiple Contraction & High Base Effect",
        ],
        "bull_drivers": [
            ("Datacenter Compute Dominance", "Datacenter revenue continues explosive expansion driven by foundational model training and enterprise inference deployment."),
            ("Blackwell Ramp & Pricing Power", "Next-generation Blackwell architecture commands higher ASPs and full-rack liquid-cooled GB200 systems expand wallet share."),
            ("Sovereign AI Infrastructure", "National governments and regional telcos invest billions in domestic AI supercomputing capacity."),
            ("Networking & Spectrum-X", "Quantum InfiniBand and Spectrum-X Ethernet networking attach rate expands to over 30% of GPU compute clusters."),
            ("Hyperscaler Capex Commitments", "Cloud titans guide elevated infrastructure capex to support accelerating multi-year AI demand."),
        ],
        "bear_drivers": [
            ("Hyperscaler Digestion & Capex Peak", "Top 4 customers represent ~40% of revenue; any capex pause creates immediate revenue deceleration."),
            ("Custom Silicon In-House Threat", "Google TPU, AWS Trainium/Inferentia, and Meta MTIA reduce reliance on third-party commercial GPUs."),
            ("Geopolitical Export Barriers", "Tightening export control thresholds risk locking out key international geographic markets."),
            ("Gross Margin Normalization", "Higher packaging costs and system-level manufacturing complexity create gross margin headwinds."),
            ("Stretched Valuation Multiples", "Trading at premium forward multiples leaves no margin of safety for quarterly execution misses."),
        ],
        "catalysts": [
            ("Blackwell GB200 Volume Shipments", "Next 1-2 Quarters", "Drives sharp revenue acceleration and full-rack system deployment."),
            ("Hyperscaler Cloud Earnings Capex Prints", "Upcoming Earnings Cycle", "Provides verified validation of sustained multi-billion compute budgets."),
            ("GTC Architecture Keynote & Software Updates", "Annual Event", "Expands enterprise software recurring revenue via CUDA and NIM microservices."),
        ],
        "long_invalidation": [
            "GAAP Gross Margin drops below 70.0% on packaging yield or system warranty costs.",
            "Top hyperscalers announce aggregate capex cuts exceeding -15% YoY.",
            "Export control thresholds expand to ban standard inference accelerators.",
        ],
        "short_invalidation": [
            "Datacenter revenue accelerates >25% QoQ beating consensus by >$2B.",
            "Gross margins expand above 78% on pure-play software mix.",
            "Hyperscaler capex guidance increases by >20% for upcoming fiscal year.",
        ],
        "metrics": [
            ("Revenue Growth", "+122% YoY", 122.0, "%"),
            ("Datacenter Revenue", "$26.3B", 26.3, "$B"),
            ("GAAP Gross Margin", "75.1%", 75.1, "%"),
            ("Capex Commitments", "$14.2B", 14.2, "$B"),
        ],
    },
    "AAPL": {
        "name": "Apple Inc.",
        "sector": "Consumer Electronics & Services",
        "long_themes": [
            "Services Ecosystem & High-Margin Recurring Revenue",
            "Apple Intelligence & On-Device AI Upgrade Cycle",
            "Custom Apple Silicon Moat & Gross Margin Expansion",
            "Installed Base Expansion Beyond 2.2B Active Devices",
            "Wearables, Spatial Computing & Enterprise Adoption",
        ],
        "short_themes": [
            "China Smartphone Market Share & Domestic Competition",
            "Regulatory Antitrust & App Store Commission Pressures",
            "Hardware Replacement Cycle Elongation",
            "Delayed AI Monetization vs Pure-Play Cloud Titans",
            "Margin Compression from Foundational Silicon Costs",
        ],
        "bull_drivers": [
            ("Services High-Margin Acceleration", "Services revenue (App Store, Cloud, Apple Pay, Subscriptions) compounds at double-digits with >74% gross margins."),
            ("Apple Intelligence Upgrade Supercycle", "On-device private AI models restrict features to recent chips, driving multi-year iPhone 16/17 replacement velocity."),
            ("Record Active Installed Base", "Over 2.2 billion active devices create an unparalleled ecosystem lock-in and lifetime customer value."),
            ("Custom M-Series & A-Series Efficiency", "In-house silicon architecture maximizes hardware margins and eliminates merchant silicon markups."),
            ("Massive Capital Return Program", "Over $100B in annual share buybacks and rising dividends provide relentless EPS support."),
        ],
        "bear_drivers": [
            ("China Market Deterioration", "Intensifying domestic competition from Huawei and state-device restrictions pressure iPhone sales volume in Greater China."),
            ("App Store Fee Regulatory Squeeze", "EU Digital Markets Act and US DOJ antitrust lawsuits threaten high-margin services take rates."),
            ("Hardware Saturation & Elongated Cycles", "Consumer smartphone upgrade cycles extend to 4+ years due to incremental annual hardware changes."),
            ("High Silicon Foundry ASPs", "Sub-3nm wafer price hikes from TSMC increase bill-of-materials costs."),
            ("Lagging Foundational AI Infrastructure", "Heavy reliance on partner cloud models limits autonomous proprietary AI ecosystem revenues."),
        ],
        "catalysts": [
            ("Apple Intelligence Feature Rollout & iOS Adoption", "Upcoming Quarter", "Triggers measurable smartphone upgrade acceleration across holiday retail."),
            ("Services Segment Quarterly Revenue Print", "Next Earnings", "Demonstrates recurring revenue durability and margin resilience."),
            ("Greater China Regional Sales Stabilization", "Next 2 Quarters", "Removes primary macro overhang on consumer hardware growth."),
        ],
        "long_invalidation": [
            "Greater China iPhone revenue declines >15% YoY for two consecutive quarters.",
            "Services gross margin contracts below 70% due to regulatory fee caps.",
            "Apple Intelligence adoption fails to accelerate upgrade rates below historical 3-year averages.",
        ],
        "short_invalidation": [
            "iPhone revenue beats consensus by >8% driven by AI upgrade cycle.",
            "Services revenue growth re-accelerates above 16% YoY.",
            "US DOJ antitrust resolution leaves core App Store take rates intact.",
        ],
        "metrics": [
            ("Services Revenue", "$24.2B", 24.2, "$B"),
            ("Services Gross Margin", "74.0%", 74.0, "%"),
            ("Installed Base", "2.2 Billion Devices", 2.2, "B"),
            ("iPhone Revenue", "$46.2B", 46.2, "$B"),
        ],
    },
    "TSLA": {
        "name": "Tesla, Inc.",
        "sector": "Automotive, Autonomy & Clean Energy",
        "long_themes": [
            "Full Self-Driving (FSD) & Cybercab Robotaxi Scaling",
            "Megapack & Commercial Energy Storage Hypergrowth",
            "Next-Gen Low-Cost Vehicle Platform ($25k Model)",
            "Optimus Humanoid Robotics Commercialization",
            "Supercharger Network Licensing & NACS Monetization",
        ],
        "short_themes": [
            "Automotive Gross Margin Compression & Price Wars",
            "Global EV Demand Slowdown & High Financing Rates",
            "Intense Chinese EV Competition (BYD, Xiaomi, Geely)",
            "Autonomous Driving Regulatory Delays & Liability",
            "High Valuation Multiples vs Traditional Auto OEMs",
        ],
        "bull_drivers": [
            ("Energy Storage Hypergrowth", "Megapack deployments accelerate >120% YoY with high software margins, becoming a major profit contributor."),
            ("FSD Software Revenue High Operating Leverage", "Unsupervised autonomy unlocks pure-software subscription margins and multi-sided Robotaxi fleet economics."),
            ("Next-Gen Unboxed Manufacturing Cost Lead", "Sub-$25k vehicle platform cuts production cost per unit by ~50%, opening mass-market global addressable market."),
            ("Optimus Humanoid Robotics", "Proprietary actuators, compute silicon, and vision AI establish first-mover leadership in industrial humanoid labor automation."),
            ("Global Supercharger Dominance", "NACS industry adoption turns North American charging infrastructure into a steady recurring utility tollbooth."),
        ],
        "bear_drivers": [
            ("Automotive Margin Deterioration", "Successive price cuts and aggressive financing incentives compress auto gross margins excluding regulatory credits below 15%."),
            ("EV Market Saturation & Subsidy Rollbacks", "Consumer demand shifts toward hybrids as high interest rates and charging concerns slow pure BEV adoption."),
            ("Chinese OEM Price War & Export Influx", "BYD and aggressive Chinese competitors undercut global pricing in Europe, Asia, and emerging markets."),
            ("Robotaxi Timeline & Regulatory Scrutiny", "Autonomous vehicle approvals face strict safety verification, limiting near-term software cash flow."),
            ("Auto Multiple Convergence Risk", "Trading at high technology multiples while core cash flow is generated by cyclical automotive manufacturing."),
        ],
        "catalysts": [
            ("Cybercab Robotaxi Production & Regulatory Approvals", "Next 6-12 Months", "Validates unsupervised autonomous software business model."),
            ("Energy Storage Quarterly Megapack Deployment Print", "Upcoming Earnings", "Confirms multi-gigawatt-hour run-rate acceleration and margin expansion."),
            ("Next-Gen Sub-$25k Vehicle Platform Unveil", "Mid-Year Horizon", "Re-accelerates automotive unit delivery volumes across mass-market segments."),
        ],
        "long_invalidation": [
            "Auto gross margin (ex-regulatory credits) contracts below 13.0%.",
            "Energy storage deployment growth decelerates below 25% YoY.",
            "FSD take rates remain below 10% on new vehicle deliveries.",
        ],
        "short_invalidation": [
            "Auto gross margins expand back above 19% on cost-down milestones.",
            "Regulatory approval for unsupervised FSD granted in major jurisdictions.",
            "Megapack quarterly gross profit exceeds $1.5B.",
        ],
        "metrics": [
            ("Energy Storage Growth", "+125% YoY", 125.0, "%"),
            ("Automotive Gross Margin", "14.6%", 14.6, "%"),
            ("Vehicle Deliveries", "462,890 units", 462890, "units"),
            ("Operating Margin", "8.2%", 8.2, "%"),
        ],
    },
    "MSFT": {
        "name": "Microsoft Corporation",
        "sector": "Enterprise Software & Cloud Infrastructure",
        "long_themes": [
            "Azure Cloud & Enterprise Generative AI Acceleration",
            "M365 Copilot Commercial Seat Expansion",
            "Enterprise Cybersecurity & Security Copilot",
            "Hyperscaler Capex Deployment & OpenAI Ecosystem",
            "Gaming & Activision Blizzard Cross-Platform Reach",
        ],
        "short_themes": [
            "Massive AI Capex Depreciation & ROI Lag",
            "Azure Cloud Growth Deceleration vs Lofty Expectations",
            "Enterprise Copilot Adoption Friction & Churn",
            "Antitrust Scrutiny on Cloud Bundling & Licensing",
            "Margin Compression from High GPU Cloud Operating Costs",
        ],
        "bull_drivers": [
            ("Azure Cloud Market Share Gains", "Azure revenue grows >28% CC with AI services contributing over 12 percentage points of incremental growth."),
            ("M365 Copilot Enterprise Monetization", "Enterprise add-on pricing of $30/seat/month unlocks billions in high-margin ARR across 400M+ commercial seats."),
            ("Comprehensive Enterprise Stack", "Integrated identity, security, data, and developer tools (GitHub, Azure, Teams) create impenetrable enterprise switching costs."),
            ("OpenAI Strategic Alliance", "Exclusive commercial cloud rights and direct foundational model access attract world's largest corporate AI workloads."),
            ("Activision Content Scale", "Acquired gaming IP and Game Pass recurring subscriptions expand high-margin consumer software footprint."),
        ],
        "bear_drivers": [
            ("Elevated Cloud Capex Burden", "Capital expenditures exceeding $18B/quarter pressure free cash flow yields and raise near-term depreciation expense."),
            ("AI Revenue Payback Horizon", "Enterprise customers conduct pilots but take longer to scale full enterprise-wide paid Copilot deployments."),
            ("Gross Margin Pressure from Compute Costs", "High cost of AI inferencing and third-party compute infrastructure compresses commercial cloud gross margins."),
            ("Regulatory Cloud Bundling Inquiries", "European Commission and FTC scrutiny into Teams/Office bundling and cloud switching penalties."),
            ("PC Market Sluggishness", "More Personal Computing OEM Windows licensing growth remains range-bound."),
        ],
        "catalysts": [
            ("Azure Cloud Quarterly AI Contribution Acceleration", "Next Earnings", "Proves sustained market share capture over AWS and GCP."),
            ("M365 Copilot Paid Seat Adoption Metrics", "Upcoming Quarter", "Confirms enterprise willingness to pay premium productivity software add-ons."),
            ("Data Center Capacity Ramps & Margin Stabilization", "6-Month Horizon", "Demonstrates efficiency gains as in-house Maia silicon deploys."),
        ],
        "long_invalidation": [
            "Azure constant-currency growth slows below 24% YoY.",
            "Commercial cloud gross margin contracts by >200bps YoY.",
            "Enterprise Copilot churn exceeds 15% across renewal cohorts.",
        ],
        "short_invalidation": [
            "Azure growth accelerates >32% YoY with AI contribution >15%.",
            "M365 Copilot ARR reaches $10B run-rate ahead of schedule.",
            "Free cash flow conversion remains resilient above 85% despite capex.",
        ],
        "metrics": [
            ("Azure Growth", "+29% YoY", 29.0, "%"),
            ("Cloud Revenue", "$38.9B", 38.9, "$B"),
            ("Commercial Gross Margin", "71.0%", 71.0, "%"),
            ("Capital Expenditures", "$19.0B", 19.0, "$B"),
        ],
    },
    "AMZN": {
        "name": "Amazon.com, Inc.",
        "sector": "E-Commerce, Cloud & Digital Advertising",
        "long_themes": [
            "AWS Cloud Re-Acceleration & Custom Silicon (Trainium/Inferentia)",
            "High-Margin Advertising Revenue Compounding",
            "North America & International Retail Operating Margin Expansion",
            "Regional Fulfillment Network Logistics Cost Reductions",
            "Generative AI Bedrock & Enterprise Model Hub",
        ],
        "short_themes": [
            "AWS Market Share Pressure from Dedicated AI Clouds",
            "Elevated Logistics & Capex Investments for Satellites / AI",
            "Consumer Discretionary Spending Weakness & Inflation Sensitivity",
            "Intense E-Commerce Competition from Discount Cross-Border Platforms",
            "Antitrust Scrutiny on Marketplace Practices & Buy Box",
        ],
        "bull_drivers": [
            ("AWS Re-Acceleration & Bedrock Adoption", "AWS annualized run-rate surpasses $105B as enterprise optimization headwinds clear and AI workloads scale on Amazon Bedrock."),
            ("Advertising High-Margin Surge", "Sponsored ads and Prime Video ad-supported tiers compound revenue >20% YoY with industry-leading contribution margins."),
            ("Fulfillment Regionalization Cost Efficiencies", "Splitting logistics into 8 regional hubs slashes shipping transit times and per-package delivery costs, driving record retail margins."),
            ("Custom Silicon (Trainium2 & Graviton4)", "In-house cost-optimized chips reduce internal compute expense and offer customers price-performance edge."),
            ("International Segment Profit Inflection", "Overseas retail operations reach sustained operating profit milestones as established markets scale."),
        ],
        "bear_drivers": [
            ("AWS AI Share Perception Lag", "Perception of lagging Microsoft Azure in enterprise LLM mindshare pressures cloud customer acquisition."),
            ("Discretionary Consumer Pressure", "Average order values in consumer electronics and apparel face price sensitivity from budget-conscious shoppers."),
            ("Capital Intensity Surge", "Massive investments in Project Kuiper satellite constellation and data center power infrastructure compress FCF."),
            ("Marketplace Competition", "Temu, Shein, and discount marketplaces aggressively target lower-ticket consumer retail categories."),
            ("Regulatory FTC Lawsuit", "Ongoing antitrust litigation targeting marketplace vendor fee structures and fulfillment requirements."),
        ],
        "catalysts": [
            ("AWS Quarterly Revenue Acceleration", "Next Earnings", "Proves cloud growth trajectory matches or exceeds peers."),
            ("North America Retail Operating Margin Expansion", "Upcoming Quarter", "Demonstrates sustained fulfillment network operating leverage."),
            ("Trainium2 Full Cluster General Availability", "Next 1-2 Quarters", "Expands in-house compute capacity and customer cost savings."),
        ],
        "long_invalidation": [
            "AWS revenue growth slows below 14% YoY.",
            "North America retail operating margin falls below 4.5%.",
            "Advertising segment growth decelerates below 12% YoY.",
        ],
        "short_invalidation": [
            "AWS revenue growth accelerates >22% YoY.",
            "Overall operating income beats consensus by >$2B.",
            "Free cash flow reaches new all-time trailing high above $60B.",
        ],
        "metrics": [
            ("AWS Growth", "+19% YoY", 19.0, "%"),
            ("AWS Revenue", "$27.5B", 27.5, "$B"),
            ("Advertising Revenue", "$14.3B", 14.3, "$B"),
            ("Consolidated Operating Income", "$17.4B", 17.4, "$B"),
        ],
    },
    "GOOGL": {
        "name": "Alphabet Inc.",
        "sector": "Search, Cloud, AI & Digital Advertising",
        "long_themes": [
            "Google Cloud Platform (GCP) Profitability & AI Momentum",
            "Gemini AI Multi-Modal Search Integration",
            "YouTube Subscriptions & High-Margin Digital Advertising",
            "Custom TPU Silicon (TPU v5p & v6e) Cost Advantage",
            "Waymo Autonomous Commercial Ride-Hail Leadership",
        ],
        "short_themes": [
            "Antitrust Remedies & Search Distribution Contracts (Apple Default)",
            "Generative AI Threat to Traditional Search Query Economics",
            "Rising Search Unit Costs from LLM Inference Computations",
            "YouTube Ad Revenue Sensitivity to Brand Spending Cycles",
            "Capex Acceleration for Data Centers Compressing Free Cash Flow",
        ],
        "bull_drivers": [
            ("GCP Operating Margin Expansion", "Google Cloud annualized run-rate surpasses $45B with operating margins expanding >11% on enterprise AI workloads."),
            ("Gemini Model Ecosystem", "Multi-modal Gemini models power AI Overviews in Search, increasing user engagement without degrading click monetization."),
            ("In-House TPU Cost Leadership", "Sixth-generation Trillium TPUs provide internal cost insulation against merchant GPU price inflation."),
            ("Waymo Autonomous Scaling", "Waymo commercial paid trips exceed 150,000/week across San Francisco, Phoenix, and LA with zero safety driver intervention."),
            ("Aggressive Capital Return & Dividend", "Over $60B in annual share repurchases and newly initiated cash dividend return cash directly to shareholders."),
        ],
        "bear_drivers": [
            ("DOJ Search Antitrust Monopoly Ruling", "Judicial remedies targeting default search engine distribution payments (e.g. $20B+ annual deal with Apple) create distribution disruption."),
            ("Search Query Disruption", "ChatGPT, Perplexity, and conversational agents threaten top-of-funnel informational search queries."),
            ("AI Search Unit Cost Inflation", "Serving AI Overviews costs multiples more per query than traditional 10-blue-links search indexing."),
            ("DOJ Ad-Tech Breakup Lawsuit", "Antitrust scrutiny threatens high-margin Google Network and ad server dominance."),
            ("High Infrastructure Capex", "Over $13B/quarter in datacenter capex reduces immediate free cash flow conversion rates."),
        ],
        "catalysts": [
            ("Google Cloud Quarterly Backlog & Margin Expansion", "Next Earnings", "Demonstrates accelerating commercial AI infrastructure profitability."),
            ("DOJ Antitrust Remedy Hearing & Settlement Framework", "Next 6 Months", "Establishes concrete visibility on search distribution agreements."),
            ("Waymo Commercial City Expansions & Fleet Scaling", "Mid-Year Horizon", "Solidifies first-mover autonomous ride-hail economics."),
        ],
        "long_invalidation": [
            "Google Search revenue growth slows below 6% YoY.",
            "GCP operating margin contracts back below 5%.",
            "Antitrust court mandates complete divestiture of Chrome or Android OS.",
        ],
        "short_invalidation": [
            "Google Cloud growth exceeds 35% YoY with margins >15%.",
            "Search revenue accelerates >14% YoY despite AI alternatives.",
            "DOJ remedy allows continuation of default revenue share agreements.",
        ],
        "metrics": [
            ("Google Cloud Growth", "+35% YoY", 35.0, "%"),
            ("Google Cloud Revenue", "$11.4B", 11.4, "$B"),
            ("Search Revenue", "$49.4B", 49.4, "$B"),
            ("Operating Margin", "32.0%", 32.0, "%"),
        ],
    },
    "AMD": {
        "name": "Advanced Micro Devices, Inc.",
        "sector": "Semiconductors & Server Processors",
        "long_themes": [
            "MI300 / MI325 AI GPU Hyperscaler Server Share Gains",
            "EPYC Server CPU Market Share Expansion vs Intel",
            "Client Ryzen AI PC Architecture Adoption",
            "ROCm Open-Source Software Stack Parity & Developer Traction",
            "Embedded & FPGA Industrial Recovery",
        ],
        "short_themes": [
            "NVIDIA CUDA Moat & Blackwell Release Speed Advantage",
            "MI300 Customer Concentration in Key Cloud Accounts",
            "Gross Margin Compression from Memory & Packaging Mix",
            "Cyclical Sluggishness in Industrial & Gaming Consoles",
            "High Valuation Multiples on Lofty AI Expectations",
        ],
        "bull_drivers": [
            ("MI300 AI GPU Revenue Surge", "Data Center GPU revenue surpasses $5.0B annual run-rate as hyperscalers deploy MI300X/MI325X as primary alternative to NVIDIA."),
            ("EPYC Server CPU Market Dominance", "Zen 5 EPYC processors capture record server market share (>35%) over legacy Intel x86 architectures."),
            ("Ryzen AI PC Leadership", "NPU-accelerated mobile processors lead next-generation enterprise and consumer Windows AI PC benchmarks."),
            ("ROCm Software Maturity", "PyTorch and vLLM day-zero support on ROCm removes migration friction for cloud inference workloads."),
            ("Operating Leverage from Foundry Mix", "TSMC sub-4nm manufacturing yield optimizations expand operating margins as volume scales."),
        ],
        "bear_drivers": [
            ("NVIDIA Blackwell Speed & Rack Scale", "NVIDIA's rapid annual cadence and NVLink rack architecture make it difficult to displace incumbent clusters."),
            ("Gaming & Console Cyclical Weakness", "PS5/Xbox console mid-cycle slowdown and discrete GPU competition weigh on non-datacenter margins."),
            ("Software Moat Disparity", "CUDA developer lock-in remains strong in training, restricting AMD largely to lower-margin inference deployments."),
            ("Embedded Inventory Digestion", "Xilinx embedded and industrial segments experience prolonged customer inventory normalization."),
            ("Execution Risk on Ambitious Targets", "Any quarterly revision to $5B+ AI GPU targets creates severe multiple compression."),
        ],
        "catalysts": [
            ("MI325X & MI350 Architecture Launch Cadence", "Upcoming Quarters", "Provides competitive response to next-generation AI silicon."),
            ("Data Center Quarterly Revenue Print", "Next Earnings", "Validates server CPU and GPU market share acceleration."),
            ("Hyperscaler Multi-Year Purchase Commitments", "6-Month Horizon", "Secures long-term capacity utilization across top cloud buyers."),
        ],
        "long_invalidation": [
            "Data Center GPU annual revenue guidance cut below $4.5B.",
            "EPYC server CPU share growth turns negative vs Intel.",
            "Gross margin contracts below 50.0%.",
        ],
        "short_invalidation": [
            "Data Center GPU revenue guidance raised above $6.5B.",
            "Overall gross margin expands above 55%.",
            "EPYC server CPU market share crosses 40% across top cloud instances.",
        ],
        "metrics": [
            ("Data Center Growth", "+122% YoY", 122.0, "%"),
            ("Data Center Revenue", "$3.5B", 3.5, "$B"),
            ("Client Segment Growth", "+29% YoY", 29.0, "%"),
            ("Gross Margin (Non-GAAP)", "54.0%", 54.0, "%"),
        ],
    },
    "SMCI": {
        "name": "Super Micro Computer, Inc.",
        "sector": "AI Server Infrastructure & Liquid Cooling",
        "long_themes": [
            "Direct-to-Chip Liquid Cooling System Leadership",
            "Time-to-Market Advantage for Next-Gen GPU Architectures",
            "Building-Block Server Solutions for Sovereign & Enterprise Clouds",
            "Hyperscaler Rack-Scale Capacity Expansion",
            "Multi-Tiered Silicon Vendor Flexibility (NVIDIA, AMD, Intel)",
        ],
        "short_themes": [
            "Internal Governance, Accounting Inquiries & Filing Delays",
            "Gross Margin Compression from Low-Margin Hyperscaler Mix",
            "Working Capital Cash Burn & High Short-Term Debt",
            "Intense Server Competition from Dell, HPE, and ODM Directs",
            "Customer Concentration & Allocation Volatility",
        ],
        "bull_drivers": [
            ("Liquid Cooling First-Mover Scale", "Proprietary direct-to-chip liquid cooling technology enables >100kW per rack deployments, critical for next-gen silicon."),
            ("Rapid Time-to-Market Execution", "Modular building-block architecture allows custom server configuration and delivery months ahead of traditional OEMs."),
            ("Massive Rack-Scale Volume", "Capacity expansion across US, Taiwan, and Malaysia reaches 5,000 server racks per month."),
            ("Multi-Vendor Component Flexibility", "Supports NVIDIA Blackwell, AMD MI300, and Intel Xeon systems, capturing diversified compute capex."),
            ("Enterprise Tier-2 Cloud Dominance", "Preferred partner for emerging AI cloud providers (CoreWeave, Lambda, Crusoe)."),
        ],
        "bear_drivers": [
            ("Accounting & Filing Integrity Overhang", "Special committee reviews and delayed SEC Form 10-K filings create corporate governance uncertainty."),
            ("Gross Margin Erosion", "Aggressive competitive bidding and high-mix customer racks compress gross margins toward single digits (~11%)."),
            ("Severe Working Capital Demands", "Financing billions in inventory and accounts receivable strains operational liquidity."),
            ("Dell & HPE Enterprise Squeeze", "Tier-1 enterprise OEMs leverage existing corporate relationships and balance sheet strength to win enterprise racks."),
            ("Customer Re-Allocation Risk", "Key customers may diversify rack assembly orders to Foxconn, Quanta, or Wistron."),
        ],
        "catalysts": [
            ("SEC Form 10-K Audited Filing Resolution", "Upcoming Milestone", "Removes primary listing and compliance uncertainty."),
            ("Liquid Cooled Blackwell Rack Shipments", "Next 1-2 Quarters", "Demonstrates production volume ramp and margin recovery."),
            ("Quarterly Gross Margin Stabilization", "Next Earnings", "Proves pricing discipline and cost pass-through on components."),
        ],
        "long_invalidation": [
            "Gross margin falls below 10.0% on competitive pricing.",
            "NASDAQ listing deficiency unresolved resulting in delisting.",
            "Key tier-2 AI cloud customers cancel or re-route major rack orders.",
        ],
        "short_invalidation": [
            "Full clean 10-K audit completed with zero material restatements.",
            "Gross margins rebound above 14% on high-density liquid cooling mix.",
            "Quarterly revenue beats consensus by >20% on Blackwell delivery ramp.",
        ],
        "metrics": [
            ("Revenue Growth", "+181% YoY", 181.0, "%"),
            ("Quarterly Revenue", "$5.9B", 5.9, "$B"),
            ("Gross Margin", "11.2%", 11.2, "%"),
            ("Rack Production Capacity", "5,000 Racks/Mo", 5000, "racks"),
        ],
    },
    "PLTR": {
        "name": "Palantir Technologies Inc.",
        "sector": "Enterprise & Government AI Operating Systems",
        "long_themes": [
            "Artificial Intelligence Platform (AIP) Bootcamp Bootstrapping",
            "US Commercial Revenue Hypergrowth & Customer Count Surge",
            "Defense & Intelligence Government Contract Moat",
            "GAAP Operating Margin Expansion & Rule of 40 Leadership",
            "S&P 500 Inclusion & Broadening Institutional Ownership",
        ],
        "short_themes": [
            "Extremely Premium Valuation Multiples (>30x Forward EV/Sales)",
            "Lumpy Government Contract Procurement Cycles",
            "International Commercial Market Resistance",
            "Intense Competition from In-House Databricks & Snowflake AI Stacks",
            "High Stock-Based Compensation & Insider Selling",
        ],
        "bull_drivers": [
            ("AIP Bootcamp Customer Flywheel", "Hands-on AIP bootcamps convert enterprise pilots into multi-million dollar annual contracts in days rather than months."),
            ("US Commercial Acceleration", "US Commercial revenue surges >54% YoY driven by enterprise adoption across healthcare, manufacturing, and energy."),
            ("Mission-Critical Defense Monopoly", "Deep integration into US DoD, Maven Smart System, and allied NATO intelligence provides sticky multi-year government cash flows."),
            ("Surging GAAP Profitability", "GAAP net margins expand >20% with Rule of 40 metrics exceeding 60% on software operating leverage."),
            ("Ontology Data Foundation Moat", "Proprietary semantic ontology architecture binds enterprise legacy data to LLMs with strict access controls."),
        ],
        "bear_drivers": [
            ("Priced for Perfection Valuation", "Trading at high forward sales multiples creates extreme downside volatility on any quarterly deceleration."),
            ("Government Spending Lumpiness", "Delays in federal budget appropriations or defense contract awards can introduce quarterly revenue lumpiness."),
            ("European & Overseas Commercial Sluggishness", "European commercial customer growth lags US momentum due to slower enterprise AI budget allocation."),
            ("Evolving Open-Source Enterprise Stacks", "Competitors like Databricks, Snowflake, and Microsoft Fabric offer customizable enterprise data layers at lower price points."),
            ("High SBC Share Dilution", "Persistent stock-based compensation expense dilutes baseline equity value."),
        ],
        "catalysts": [
            ("US Commercial Customer Count Acceleration", "Next Earnings", "Validates rapid scaling of AIP enterprise software adoption."),
            ("Major DoD Titan / Maven Defense Contract Expansion", "Upcoming Months", "Solidifies long-term government recurring backlog."),
            ("GAAP Operating Margin Expansion Print", "Next Quarter", "Confirms software operating leverage and cash generation power."),
        ],
        "long_invalidation": [
            "US Commercial revenue growth slows below 25% YoY.",
            "GAAP operating margin contracts below 15%.",
            "Net retention rate drops below 105%.",
        ],
        "short_invalidation": [
            "US Commercial growth accelerates >65% YoY.",
            "Rule of 40 score exceeds 75%.",
            "DoD contract awards expand annualized government run-rate by >30%.",
        ],
        "metrics": [
            ("US Commercial Growth", "+54% YoY", 54.0, "%"),
            ("GAAP Net Margin", "20.2%", 20.2, "%"),
            ("Rule of 40 Score", "68%", 68.0, "%"),
            ("US Commercial Customers", "+83% YoY", 83.0, "%"),
        ],
    },
    "INTC": {
        "name": "Intel Corporation",
        "sector": "Semiconductors & Foundry Services",
        "long_themes": [
            "Intel Foundry 18A Process Node Technology Execution",
            "Xeon 6 Server Processors & Enterprise Cost Leadership",
            "CHIPS Act Federal Grants & Capital Subsidies",
            "Restructuring Cost Reductions & Asset Optimization",
            "Gaudi 3 AI Accelerator Value Proposition",
        ],
        "short_themes": [
            "Massive Foundry Operating Losses & Yield Uncertainty",
            "Persistent Server CPU Market Share Losses to AMD",
            "Dividend Suspension & Strained Free Cash Flow",
            "Lagging Commercial Generative AI Accelerator Footprint",
            "Execution Risks on High-NA EUV Mass Production",
        ],
        "bull_drivers": [
            ("18A Process Node Turnaround", "First foundry to deploy RibbonFET gate-all-around and PowerVia backside power delivery, targeting process leadership in 2026."),
            ("Xeon 6 Server Rebound", "Sierra Forest efficiency cores and Granite Rapids performance cores stabilize enterprise datacenter sockets."),
            ("CHIPS Act & Sovereign Subsidies", "Receives over $8.5B in direct federal grants plus billions in tax credits, subsidizing domestic manufacturing expansion."),
            ("Aggressive Cost Restructuring", "$10B+ cost reduction plan (15% headcount reduction and capex moderation) lowers structural break-even point."),
            ("Deep Value Multiples", "Trading near tangible book value limits downside if operational turnaround achieves milestone execution."),
        ],
        "bear_drivers": [
            ("Foundry Operating Bleed", "Intel Foundry reports billions in quarterly operating losses with multi-year cash flow burn before reaching breakeven."),
            ("Server CPU Socket Loss to AMD EPYC", "AMD continues capturing high-margin cloud hyperscaler sockets, eroding Intel's historical cash cow."),
            ("Zero AI Accelerator Market Share", "Gaudi 3 revenue trajectory remains immaterial compared to NVIDIA Blackwell and AMD MI300."),
            ("Strained Balance Sheet & Dividend Cut", "Suspended dividend and negative free cash flow limit capital return to shareholders."),
            ("Foundry Customer Signing Uncertainty", "External fabless chipmakers take a cautious approach before committing high-volume wafer tape-outs to IFS."),
        ],
        "catalysts": [
            ("Intel 18A High-Volume Manufacturing Milestones", "Next 2 Quarters", "Critical test of manufacturing turnaround and packaging yields."),
            ("External Anchor Customer Commitments for IFS", "Upcoming Milestone", "Validates third-party commercial viability of Intel Foundry."),
            ("Restructuring Operating Expense Reductions", "Upcoming Earnings", "Demonstrates structural cash burn reduction."),
        ],
        "long_invalidation": [
            "Intel 18A process slips past committed 2026 production schedule.",
            "Quarterly Foundry operating losses widen beyond -$3.5B.",
            "Datacenter & AI segment revenue declines >15% YoY.",
        ],
        "short_invalidation": [
            "Major fabless titan (Apple, Qualcomm, or NVIDIA) announces external 18A foundry contract.",
            "Foundry operating losses narrow significantly ahead of internal roadmap.",
            "Xeon 6 captures >50% of new cloud server deployments.",
        ],
        "metrics": [
            ("Foundry Loss", "-$2.8B", -2.8, "$B"),
            ("Client Segment Revenue", "$7.3B", 7.3, "$B"),
            ("Gross Margin (GAAP)", "38.0%", 38.0, "%"),
            ("CHIPS Act Direct Funding", "$8.5B", 8.5, "$B"),
        ],
    },
}


def get_profile_for_ticker(ticker: str) -> dict[str, Any]:
    """Returns specialized profile for known tickers or generates a customized heuristic profile for any symbol."""
    sym = ticker.upper().strip()
    if sym in COMPANY_PROFILES:
        return COMPANY_PROFILES[sym]

    # Dynamic profile for any other ticker symbol
    return {
        "name": f"{sym} Corporation",
        "sector": "Equity Asset / Enterprise Operations",
        "long_themes": [
            f"{sym} Core Revenue & Operational Market Expansion",
            f"{sym} Pricing Power & Operating Margin Leverage",
            f"{sym} Capital Allocation & Shareholder Value Generation",
            f"{sym} Digital Transformation & Product Innovation",
            f"{sym} Favorable Secular Demand & Macro Tailwinds",
        ],
        "short_themes": [
            f"{sym} Revenue Growth Deceleration & Demand Softness",
            f"{sym} Input Cost Pressures & Gross Margin Compression",
            f"{sym} Competitive Encroachment & Market Share Loss",
            f"{sym} Capital Expenditure Intensity & Cash Burn",
            f"{sym} Stretched Valuation & Macroeconomic Cyclical Sensitivity",
        ],
        "bull_drivers": [
            (f"{sym} Operational Growth Engine", f"{sym} demonstrates accelerating revenue and strong product execution across its primary business segments."),
            (f"{sym} Margin Expansion & Operating Leverage", "Cost discipline and pricing power drive margin expansion and expanding cash flow conversion."),
            (f"{sym} Market Share Capture", "Strategic positioning and product quality enable sustainable competitive moat and customer acquisition."),
            (f"{sym} Strong Balance Sheet & Capital Return", "Healthy cash reserves and resilient cash generation support disciplined reinvestment and shareholder return."),
            (f"{sym} Long-Term Secular Tailwinds", "Exposure to growing addressable markets provides multi-year expansion visibility."),
        ],
        "bear_drivers": [
            (f"{sym} Revenue Deceleration", "Core business segments face demand moderation and extended customer purchasing cycles."),
            (f"{sym} Margin Compression & Cost Inflation", "Rising operational expenditures and competitive price pressure squeeze operating margins."),
            (f"{sym} Competitive Intensity", "Aggressive competitors challenge market share and force increased marketing and R&D expenditures."),
            (f"{sym} High Valuation Multiple Risk", "Valuation reflects optimistic growth assumptions with limited margin of safety for execution stumbles."),
            (f"{sym} Macro & Regulatory Headwinds", "Broader macroeconomic volatility and tightening industry regulations create operational friction."),
        ],
        "catalysts": [
            (f"{sym} Upcoming Quarterly Earnings & Guidance Print", "Next Earnings", "Validates operational execution and margin trajectory."),
            (f"{sym} Strategic Product Announcements & Expansions", "Upcoming Quarters", "Provides catalysts for market share expansion."),
            (f"{sym} Capital Allocation & Balance Sheet Updates", "Next 6 Months", "Demonstrates cash conversion and capital efficiency."),
        ],
        "long_invalidation": [
            f"Core segment revenue declines >10% YoY for two consecutive quarters.",
            f"Operating margin contracts by >300bps YoY.",
            f"Key customer churn accelerates significantly.",
        ],
        "short_invalidation": [
            f"Revenue beats consensus by >10% with accelerating forward guidance.",
            f"Operating margins expand by >300bps YoY.",
            f"New major strategic partnership or high-margin contract announced.",
        ],
        "metrics": [
            (f"{sym} Revenue Growth", "+15% YoY", 15.0, "%"),
            (f"{sym} Operating Margin", "22.5%", 22.5, "%"),
            (f"{sym} Free Cash Flow", "$3.5B", 3.5, "$B"),
        ],
    }
