/**
 * The floor's guard rails — one test per way the room could lie.
 *
 * Run: `node --experimental-strip-types --test src/app/clark/studio/desk/floor/floorPlan.test.ts`
 *
 * The CDO spec (docs/design/CDO_AUDIT_2026-08-20.md, Deliverable B) states seven
 * acceptance criteria, each with a named falsifier. Four of them are assertions
 * about derived facts and are pinned HERE; the other three (bundle delta, theme
 * tokens, no new dependencies) are properties of the built artifact and are
 * measured on the worktree, not asserted in a unit test — stated so a reader of
 * this file does not conclude the suite covers all seven.
 *
 * The failure this file exists to make impossible: **an animated floor that
 * moves when nothing happened.** Ambient traffic on a room that claims to show
 * real traffic is the visual form of rendering an absent number as zero — it
 * reads as a busy firm and is generated by a timer.
 */

import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

import type { SpineEvent } from "@/lib/fund_api";
import { SEATS } from "../seatLib.ts";
import { faceFor } from "../faces.ts";
import {
  BENCH_ORDER,
  CAMERA_TRANSFORM,
  CHAIN,
  CORRIDOR,
  EXEC_ROW,
  FIXTURES,
  PLANE_PX,
  allSpots,
  benchSpots,
  corridorHasNoShortcut,
  floorEnabledFrom,
  floorPulses,
  awaitingReviewSeats,
  litSeats,
  pulsesByWire,
  reviewDetectionBlind,
  roomState,
  runsChip,
  screenSeparation,
  spotById,
  wallClearance,
} from "./floorPlan.ts";

/* ------------------------------------------------------------------ flag --- */

test("the floor is off unless NEXT_PUBLIC_STUDIO_FLOOR is exactly 1", () => {
  assert.equal(floorEnabledFrom(undefined), false);
  assert.equal(floorEnabledFrom(null), false);
  assert.equal(floorEnabledFrom(""), false);
  assert.equal(floorEnabledFrom("0"), false);
  // "true" is not 1. The spec names the value; a flag that accepts anything
  // truthy is a flag that turns itself on in an environment nobody checked.
  assert.equal(floorEnabledFrom("true"), false);
  assert.equal(floorEnabledFrom("1"), true);
});

test("the flag is read as a LITERAL process.env member, or the browser never sees it", () => {
  // The incident this pins (builder D5, found by screenshot): `floorEnabled`
  // originally took `env = process.env` as a parameter. Next inlines
  // NEXT_PUBLIC_* only where the member access is written out literally, so in
  // the browser the injected object was empty and the room reported itself
  // "not enabled" with the flag set. A unit test cannot see webpack, so this
  // asserts on the SOURCE: the literal read must be present and must not be
  // reachable through an injected bag.
  const src = readFileSync(
    new URL("./floorPlan.ts", import.meta.url), "utf8");
  assert.match(src, /floorEnabledFrom\(process\.env\.NEXT_PUBLIC_STUDIO_FLOOR\)/,
    "the literal member access is gone — the browser will read an empty env");
  assert.doesNotMatch(src, /=\s*process\.env\s*\)/,
    "process.env is being passed as an object again; Next will not inline it");
});

/* ------------------------------------------------- geometry = org chart ---- */

test("the exec row is the reporting line: corner office, triage, the meter, record, console", () => {
  // Donna joined 2026-08-21, beside Vishesh (brief Part B). Grace joined
  // 2026-08-22 (CEO: "CFO desk needs to be visible in the room too"). The row
  // is the reporting line: the CEO decides, the COO batches, the CFO argues
  // with the COO, the secretary records, the CTO dispatches.
  assert.deepEqual(EXEC_ROW.map((s) => s.id), ["ceo", "coo", "cfo", "secretary", "cto"]);
  // Left to right along the back wall, and the corner office is IN the corner.
  const xs = EXEC_ROW.map((s) => s.at.x);
  assert.deepEqual([...xs].sort((a, b) => a - b), xs);
  assert.ok(EXEC_ROW[0].at.x < 25, "the corner office must sit against the wall");
});

test("the two seats the constitution makes argue are drawn ADJACENT", () => {
  // THE EXECUTIVE TABLE (constitution, 2026-08-22): the COO and the CFO advise
  // the same person on the same decisions from different axes and are expected
  // to argue — "Vishesh ranks by what cannot be taken back; Grace ranks by what
  // moves the date." On this floor the geometry IS the org chart, so seating
  // them at opposite ends of the row would be drawing something false. This
  // fails if a future re-order slides another desk between them.
  const ids = EXEC_ROW.map((s) => s.id);
  assert.equal(Math.abs(ids.indexOf("coo") - ids.indexOf("cfo")), 1,
    "the COO and the CFO are peers who argue; the room must not seat them apart");
});

test("exactly ONE inbox tray exists, and it is in the corner office", () => {
  // The spec's sharpest sentence: the approval queue lives there and only
  // there. A second tray anywhere on this floor would draw a second place the
  // click could live, which is the one thing the constitution says is false.
  const trays = allSpots().filter((s) => s.inboxTray);
  assert.equal(trays.length, 1);
  assert.equal(trays[0].id, "ceo");
  const triage = allSpots().filter((s) => s.triageTray);
  assert.equal(triage.length, 1);
  assert.equal(triage[0].id, "coo", "the triage tray feeds the corner office; it is not one");
});

test("the bench is in CONSTITUTION order, two rows of four, and no exec-row seat is on it", () => {
  // The coo (2026-08-20), the secretary (2026-08-21) and the cfo (2026-08-22)
  // have exec-row desks. A seat drawn in BOTH places would appear twice in one
  // room, which is the failure this assertion caught the day Donna was added.
  //
  // EIGHT IS CHECKED, NOT ASSUMED. Grace's arrival added a seat to SEATS AND a
  // desk to the exec row in the same change, so the bench held at eight and
  // still fills 4x2 exactly. Had only one half landed, this is the line that
  // fails — either a nine-seat bench with a row of one, or a duplicate desk.
  assert.equal(BENCH_ORDER.length, 8);
  assert.deepEqual([...BENCH_ORDER],
    SEATS.filter((s) => s !== "coo" && s !== "secretary" && s !== "cfo"));
  for (const id of ["coo", "secretary", "cfo"]) {
    assert.ok(!BENCH_ORDER.includes(id as never), `${id} is on the bench AND the exec row`);
  }
  // The exec row and the bench between them must cover EVERY seat: a colleague
  // who is on the roster and on neither is simply not in the room.
  const drawn = new Set<string>([...EXEC_ROW.map((s) => s.id), ...BENCH_ORDER]);
  for (const s of SEATS) assert.ok(drawn.has(s), `${s} has no desk anywhere on this floor`);
  const spots = benchSpots();
  assert.equal(spots.length, 8);
  const rows = new Set(spots.map((s) => s.at.y));
  assert.equal(rows.size, 2, "two rows");
  for (const y of rows) {
    assert.equal(spots.filter((s) => s.at.y === y).length, 4, "of four");
  }
  // Reading order within a row is constitution order, not alphabetical and not
  // whatever /fund/desk returned. The live roster today hands back builder
  // before riskofficer; the floor must not inherit that.
  const first = spots.filter((s) => s.at.y === spots[0].at.y);
  assert.deepEqual(first.map((s) => s.id), ["mechanism", "analyst", "pm", "quant"]);
});

test("every desk's accessible sentence comes from faces.ts, verbatim", () => {
  // Criterion 5. A hand-written second copy of "what the adversary does" is a
  // second thing to drift, and the drift would be invisible: both sentences
  // read fine, only one is the registry's.
  for (const s of benchSpots()) {
    const f = faceFor(s.id);
    assert.ok(f, `no face for ${s.id}`);
    assert.equal(s.says, f!.role);
  }
});

test("Abhishek's wing is a DOOR with no interior, and it opens his existing page", () => {
  const door = spotById("thesis-door");
  assert.ok(door);
  assert.equal(door!.kind, "door");
  assert.equal(door!.href, "/clark/studio/thesis");
  assert.match(door!.label, /observe only/);
  // Nothing else in the room may point into the thesis surface — the floor
  // draws a door, never a room.
  const inside = allSpots().filter(
    (s) => s.id !== "thesis-door" && (s.href || "").includes("/thesis"),
  );
  assert.deepEqual(inside, []);
});

test("the auto-policy is a caged MACHINE by the venue door, never a colleague", () => {
  const cage = spotById("autopolicy-cage");
  const venue = spotById("venue-door");
  assert.ok(cage && venue);
  assert.equal(cage!.kind, "machine");
  assert.equal(cage!.href, null, "the cage is not a door — nothing on this floor opens it");
  // "beside the venue door" is a measurable claim, so it is measured.
  const d = Math.hypot(cage!.at.x - venue!.at.x, cage!.at.y - venue!.at.y);
  assert.ok(d < 20, `the cage is ${d.toFixed(1)} units from the venue door — not beside it`);
  // Neither fixture may light: a machine is not "working".
  assert.ok(!cage!.lampable && !venue!.lampable);
});

test("no fixture is lampable, and every bench seat is", () => {
  for (const f of FIXTURES) {
    assert.ok(!f.lampable, `${f.id} is a fixture and must never light as a working seat`);
  }
  for (const s of benchSpots()) assert.ok(s.lampable);
});

/* ----------------------------------------------- the chain as a corridor --- */

test("the corridor walks the constitution's chain and offers NO shortcut", () => {
  assert.deepEqual([...CHAIN], ["mechanism", "adversary", "cto", "machine-room", "ceo"]);
  assert.ok(corridorHasNoShortcut(),
    "the aisle reaches a station out of chain order, or skips one — a shortcut " +
    "aisle draws a path the constitution does not have");
  // ONE polyline: every station lies ON it, and it is a single unbranched run
  // of points (no point repeats, which is what a branch would require).
  const seen = new Set(CORRIDOR.map((p) => `${p.x},${p.y}`));
  assert.equal(seen.size, CORRIDOR.length, "a repeated waypoint is a branch");
  for (const id of CHAIN) {
    const s = spotById(id)!;
    assert.ok(CORRIDOR.some((p) => p.x === s.at.x && p.y === s.at.y),
      `${id} is a chain station but the aisle does not reach it`);
  }
});

test("every corridor segment is an aisle, not a diagonal short-cut across desks", () => {
  // Two consecutive waypoints may differ on at most one axis OR be the single
  // dog-leg into the machine room. A free diagonal would let a future edit draw
  // mechanism→ceo as one straight line and still pass the ordering test above.
  let diagonals = 0;
  for (let i = 1; i < CORRIDOR.length; i++) {
    const a = CORRIDOR[i - 1], b = CORRIDOR[i];
    if (a.x !== b.x && a.y !== b.y) diagonals += 1;
  }
  assert.ok(diagonals <= 2, `${diagonals} diagonal aisle segments — the room is being cut across`);
});

/* ---------------------------------------------------------- the room state -- */

test("a dead spine is UNLIT, and is not the same fact as a quiet room", () => {
  // Criterion 3. Either read failing darkens the room.
  assert.equal(roomState({ deskReadable: false, monitorReadable: true, halted: false }), "dead");
  assert.equal(roomState({ deskReadable: true, monitorReadable: false, halted: false }), "dead");
  assert.equal(roomState({ deskReadable: true, monitorReadable: true, halted: false }), "lit");
  assert.equal(roomState({ deskReadable: true, monitorReadable: true, halted: true }), "halted");
  // A monitor that did not report `halted` is not a monitor reporting calm —
  // but it IS readable, so the room stays lit and the strip stays dark. The
  // RiskBar owns the sentence about an unreachable monitor; the floor must not
  // invent a second, softer one.
  assert.equal(roomState({ deskReadable: true, monitorReadable: true, halted: null }), "lit");
});

test("a dead spine hides COUNTS, and must not invent a chip on a human or a machine", () => {
  // THE DEFECT THIS PINS WAS LIVE UNTIL 2026-08-22 AND WAS FOUND BY LOOKING.
  // Floor.tsx read `state === "dead" ? null : runsToday(spot)`. The first half
  // is right — a stale count on an unreadable spine reads as measured — but it
  // collapsed `undefined` into `null` on the way, and `undefined` is not a
  // missing count, it is "this is not a dispatched seat at all". Result: a ×?
  // on Neelesh's desk, on Fable's, on the machine room, on the caged
  // auto-policy, on the venue door and on Abhishek's thesis door. Seventeen
  // spots, seventeen chips, measured off the live DOM.
  //
  // The three returns are three facts and the rule keeps them three.
  assert.equal(runsChip("lit", 3), 3);
  assert.equal(runsChip("lit", 0), 0, "a measured zero is a measurement");
  assert.equal(runsChip("halted", 5), 5, "a halt is not an unreadable spine");
  assert.equal(runsChip("lit", null), null, "an unread count is ×?, never 0");
  // Dead: counts become ×?, because unknown must not read as measured.
  assert.equal(runsChip("dead", 3), null);
  assert.equal(runsChip("dead", 0), null);
  assert.equal(runsChip("dead", null), null);
  // Dead: a NON-SEAT stays a non-seat. This is the regression.
  assert.equal(runsChip("dead", undefined), undefined,
    "a dead spine put a runs chip on the CEO, the CTO and every fixture");
  assert.equal(runsChip("lit", undefined), undefined);
  assert.equal(runsChip("halted", undefined), undefined);
});

test("no roster means NO lamps — never 'everyone idle'", () => {
  assert.deepEqual(litSeats(null), []);
  assert.deepEqual(litSeats(undefined), []);
  const roster = [
    { agent: "pm", activity: { status: "working" } },
    { agent: "quant", activity: { status: "idle" } },
    // A roster row with no activity block at all: absent, so unlit.
    { agent: "analyst" },
  ] as unknown as Parameters<typeof litSeats>[0];
  assert.deepEqual(litSeats(roster), ["pm"]);
});

/* ------------------------------------------------------------- the pulses -- */

const ev = (
  type: string, id: string, ts: string, actor: string,
  payload: Record<string, unknown>,
): SpineEvent => ({
  event_id: id, type, ts, actor, payload,
} as unknown as SpineEvent);

test("pulse count equals desk-event count, and every pulse carries a real event id", () => {
  // Criterion 4, the replay test. Its falsifier: a pulse whose event_id is not
  // in the source log, or a count that exceeds the events supplied.
  const events = [
    ev("DeskRequested", "e1", "2026-08-21T10:00:00Z", "ceo",
       { serves: "pm", subject: "review the sleeve" }),
    ev("DeskDispatched", "e2", "2026-08-21T10:01:00Z", "cto",
       { seat: "pm", task_id: "r1", task: "sleeve v2" }),
    ev("DeskRequestResolved", "e3", "2026-08-21T10:02:00Z", "cto",
       { request_id: "r1", resolution: "docs/pm/X.md" }),
    ev("DeskRecommendationDecided", "e4", "2026-08-21T10:03:00Z", "ceo",
       { seat: "pm", status: "accepted", text: "trim GLD" }),
    // Not desk traffic. Must draw nothing: the room shows the DESK's wire.
    ev("OrderApproved", "e5", "2026-08-21T10:04:00Z", "ceo", { approver: "ceo" }),
    ev("NavStruck", "e6", "2026-08-21T10:05:00Z", "system", { total_nav_usd: 2011.81 }),
  ];
  const { pulses, total } = floorPulses(events, 50);
  assert.equal(total, 4, "only the four desk event types are traffic");
  assert.equal(pulses.length, 4, "one pulse per desk event, no more and no fewer");
  const ids = new Set(events.map((e) => e.event_id));
  for (const p of pulses) {
    assert.ok(ids.has(p.eventId), `pulse ${p.eventId} has no event behind it`);
  }
  assert.equal(new Set(pulses.map((p) => p.eventId)).size, 4, "no event drawn twice");
});

test("an empty log draws an empty room — there is no ambient traffic branch", () => {
  // The single most important assertion in this file. If the floor ever grows a
  // decorative animation, this is where it shows up.
  assert.deepEqual(floorPulses([], 50), { pulses: [], total: 0 });
  assert.deepEqual(floorPulses(null, 50), { pulses: [], total: 0 });
  assert.deepEqual(floorPulses(undefined, 50), { pulses: [], total: 0 });
});

test("the drawn window is clipped newest-first and the total is reported, never implied", () => {
  const events = Array.from({ length: 30 }, (_, i) =>
    ev("DeskDispatched", `e${i}`, `2026-08-21T10:${String(i).padStart(2, "0")}:00Z`,
       "cto", { seat: "pm", task_id: `r${i}`, task: `t${i}` }));
  const { pulses, total } = floorPulses(events, 5);
  assert.equal(total, 30, "the total counts every desk event read, not the drawn window");
  assert.equal(pulses.length, 5);
  assert.deepEqual(pulses.map((p) => p.eventId), ["e29", "e28", "e27", "e26", "e25"]);
});

test("a delivery names its sender by matching the dispatch, and says so when it cannot", () => {
  // DeskRequestResolved carries {request_id, resolution, actor, trace_id} and
  // NO seat — verified on the live log 2026-08-21. Guessing a seat here would
  // draw an artifact arriving from a desk that never sent it.
  const matched = floorPulses([
    ev("DeskDispatched", "d1", "2026-08-21T09:00:00Z", "cto",
       { seat: "validator", task_id: "req-1", task: "audit" }),
    ev("DeskRequestResolved", "r1", "2026-08-21T09:30:00Z", "cto",
       { request_id: "req-1", resolution: "docs/AUDIT.md" }),
  ], 50).pulses.find((p) => p.eventId === "r1")!;
  assert.equal(matched.fromId, "validator");
  assert.equal(matched.toId, "cto");
  assert.equal(matched.verb, "delivered");
  assert.equal(matched.offFloor, null);

  const orphan = floorPulses([
    ev("DeskRequestResolved", "r2", "2026-08-21T09:30:00Z", "cto",
       { request_id: "req-missing", resolution: "docs/X.md" }),
  ], 50).pulses[0];
  assert.equal(orphan.fromId, null);
  assert.match(orphan.offFloor!, /outside the events read/);
  // It still counts. An unattributable delivery is a fact about the record.
  assert.equal(floorPulses([
    ev("DeskRequestResolved", "r2", "2026-08-21T09:30:00Z", "cto",
       { request_id: "req-missing", resolution: "docs/X.md" }),
  ], 50).total, 1);
});

test("a seat with no desk on this floor is NAMED, not dropped and not drawn as someone else", () => {
  // `cdo-trial` is a real seat on the live log with no chair in this room.
  const p = floorPulses([
    ev("DeskRecommendationDecided", "x1", "2026-08-21T11:00:00Z", "ceo",
       { seat: "cdo-trial", status: "accepted", text: "the floor spec" }),
  ], 50).pulses[0];
  assert.equal(p.fromId, "ceo");
  assert.equal(p.toId, null);
  assert.match(p.offFloor!, /cdo-trial/);
  assert.match(p.offFloor!, /no desk on this floor/);
});

test("wires group pulses without losing any — reduced motion must lose no information", () => {
  // Criterion 2's information-parity half: under the media query the moving dot
  // is replaced by a dashed aisle plus a COUNT CHIP, and the count comes from
  // here. If grouping ever dropped a pulse, the chip would under-report and the
  // reduced-motion reader would see a calmer firm than the animated one.
  const events = [
    ev("DeskDispatched", "a", "2026-08-21T10:00:00Z", "cto", { seat: "pm", task_id: "1" }),
    ev("DeskDispatched", "b", "2026-08-21T10:01:00Z", "cto", { seat: "pm", task_id: "2" }),
    ev("DeskDispatched", "c", "2026-08-21T10:02:00Z", "cto", { seat: "quant", task_id: "3" }),
    ev("DeskRecommendationDecided", "d", "2026-08-21T10:03:00Z", "ceo",
       { seat: "cdo-trial", status: "accepted" }),
  ];
  const { pulses } = floorPulses(events, 50);
  const wires = pulsesByWire(pulses);
  const onWires = wires.reduce((n, w) => n + w.pulses.length, 0);
  const offFloor = pulses.filter((p) => !p.fromId || !p.toId).length;
  assert.equal(onWires + offFloor, pulses.length,
    "every pulse is either on a wire or explicitly off-floor — none may vanish");
  const toPm = wires.find((w) => w.key === "cto>pm")!;
  assert.equal(toPm.pulses.length, 2);
});

/* ---------------------------------------------------------------- camera --- */

test("the camera is fixed, orthographic and dimetric — no perspective, ever", () => {
  // The spec forbids free cameras and lighting; a perspective camera would also
  // make the BACK of the room (where the approvals are) the smallest thing on
  // screen. One rotate pair, no perspective(), no scale.
  assert.ok(!CAMERA_TRANSFORM.includes("perspective"));
  assert.ok(!CAMERA_TRANSFORM.includes("scale"));
  assert.equal((CAMERA_TRANSFORM.match(/rotate/g) || []).length, 2);
});

/* ------------------------------------------------ Donna joins the floor --- */

test("the secretary has an exec-row desk, a route and a face", () => {
  // Brief Part B: "executive row beside Vishesh". Before this she had no desk,
  // no seat page and no face — a colleague who had already run, invisible on
  // the floor and unattributed on the CEO's desk.
  const d = spotById("secretary");
  assert.ok(d, "no secretary desk on the floor");
  assert.equal(d!.href, "/clark/studio/desk/secretary");
  assert.equal(d!.at.y, EXEC_ROW[0].at.y, "she is on the back wall with the others");
  assert.ok(faceFor("secretary"), "no face on file for the secretary");
  assert.equal(faceFor("donna")?.id, "secretary", "her name must reach her face");
});

/* ------------------------------------------------ Grace joins the floor --- */

test("the cfo has an exec-row desk, a route the whitelist knows, and a face", () => {
  // CEO, 2026-08-22: "CFO desk needs to be visible in the room too". Grace was
  // seated in the constitution, had been dispatched and had recorded a run, and
  // the room did not draw her — the spine had already been fixed (GET /fund/desk
  // returns 11 roster seats with cfo present) and only the UI was behind.
  const d = spotById("cfo");
  assert.ok(d, "no cfo desk on the floor");
  assert.equal(d!.label, "Grace");
  assert.equal(d!.at.y, EXEC_ROW[0].at.y, "she is on the back wall with the others");
  assert.ok(d!.lampable, "she is a dispatched seat and her desk must be able to light");
  // The desk is a DOOR, and a door that 404s is worse than no door: the route
  // whitelist has to carry her too. This is the assertion that would have
  // caught a floor desk added without the seatLib change.
  assert.equal(d!.href, "/clark/studio/desk/cfo");
  assert.ok((SEATS as readonly string[]).includes("cfo"),
    "the cfo desk links to a route the seat whitelist rejects — it will 404");
  assert.ok(faceFor("cfo"), "no face on file for the cfo");
  assert.equal(faceFor("grace")?.id, "cfo", "her name must reach her face");
  // Her sentence has to carry the SEAT's point, not its title. The scarce
  // resource is the clock (CEO, same day), and every allocation is judged on
  // whether it moves the date — a desk plaque reading "CFO — finance" would be
  // a label where the room promises a job.
  assert.match(d!.says, /clock/);
  assert.match(d!.says, /date/);
});

test("the exec row stays evenly spaced after the fifth desk", () => {
  // The row was re-spaced from three to four (Donna, 2026-08-21) and from four
  // to five (Grace, 2026-08-22) rather than squeezing anyone in: exec spacing
  // was 23-25 units when the row held three and the bench's is ~20, so an
  // inserted desk at ~11 units would have overlapped its neighbours.
  //
  // 18 UNITS IS NOT A TASTE, it is the arithmetic of the camera. One unit of
  // pure-x travel is sqrt((PLANE_PX/100/√2)² + (PLANE_PX/100·cos58°/√2)²) =
  // 6.08 screen px at PLANE_PX=760, so 18 units is 109px between centres
  // against the widest measured exec card (the COO's, 75px with its triage
  // tray). The row runs at 19 today, i.e. 116px.
  const xs = EXEC_ROW.map((s) => s.at.x);
  const gaps = xs.slice(1).map((x, i) => x - xs[i]);
  assert.ok(Math.min(...gaps) >= 18,
    `exec desks are ${Math.min(...gaps)} units apart — they will overlap`);
  assert.ok(Math.max(...gaps) - Math.min(...gaps) <= 3, "the row is uneven");
});

test("no two pieces of furniture overlap ON SCREEN, which is the space that matters", () => {
  // Room-unit distance is the WRONG measure and a test that used it would pass
  // while the room read as a pile: the camera squashes y to cos(58°) = 53% and
  // spins the plane 45°, so two desks 12 units apart vertically are far closer
  // than two 12 units apart on the diagonal. `screenSeparation` is that
  // projection, validated against the live DOM (it predicted the console card
  // 33.4px below the plane's top edge; getBoundingClientRect measured 34).
  //
  // 85px is measured, not chosen. Desk cards rendered 68-75px wide (CDP,
  // 2026-08-22, 17 spots), so the widest possible pair of desks needs 75px of
  // centre separation to stop touching and 85 leaves 10px of aisle. Today's
  // tightest pair is quant/machine-room at 88.4px — this test has almost no
  // slack in it on purpose: the next desk inserted here should have to think.
  const spots = allSpots();
  let worst = { pair: "", d: Infinity };
  for (let i = 0; i < spots.length; i++) {
    for (let k = i + 1; k < spots.length; k++) {
      const d = screenSeparation(spots[i].at, spots[k].at);
      if (d < worst.d) worst = { pair: `${spots[i].id} / ${spots[k].id}`, d };
    }
  }
  assert.ok(worst.d >= 85,
    `${worst.pair} are ${worst.d.toFixed(1)}px apart on screen — their cards touch`);

  // The thesis door is the exception the room has to route around: its plaque
  // reads "thesis — observe only" and measured 117px, so its neighbours need
  // 92.5px before anything else does — nothing else in the room does. This
  // assertion is also what said the door did NOT have to move in the
  // 2026-08-22 re-space: an intermediate pass shifted it to (2,32), which
  // measured 105.6px to the corner office, and (3,34) measures 119.4px. It
  // stayed. Today's tightest neighbour is the mechanism's desk at 113.7px.
  const door = spotById("thesis-door")!;
  for (const s of spots) {
    if (s.id === door.id) continue;
    const d = screenSeparation(s.at, door.at);
    assert.ok(d >= 100,
      `${s.id} is ${d.toFixed(1)}px from the thesis door, whose 117px plaque needs 100`);
  }
});

test("every desk STANDS ON the floor — nothing hangs over a wall but a door", () => {
  // THE DEFECT THIS PINS WAS FOUND BY LOOKING, 2026-08-22, and every assertion
  // in this file passed while it was live. The first pass of the re-space put
  // the machine room at x=94 and the venue door at (96,84); both cards rendered
  // hanging past the floor's right edge with nothing underneath them. In room
  // units nothing was wrong — 94 is comfortably inside 0..100 — because the
  // failure is the CARD's pixel width against the wall's projected distance,
  // and until `wallClearance` existed those two lived in different spaces.
  //
  // 38px is half the widest measured desk card (75px, the COO's with its triage
  // tray), so a spot at exactly this clearance has its card's far edge on the
  // wall. Today's tightest is the corner office at 40px, which is correct: a
  // corner office is supposed to be in the corner.
  for (const s of allSpots()) {
    if (s.kind === "door") continue;  // a door is IN a wall; its plaque straddles one
    const c = wallClearance(s.at);
    assert.ok(c >= 38,
      `${s.id} sits ${c.toFixed(0)}px from the nearest wall — its card hangs off the floor`);
  }
  // And the exemption is narrow: the two doors are the only spots that may.
  const doors = allSpots().filter((s) => s.kind === "door").map((s) => s.id);
  assert.deepEqual(doors.sort(), ["thesis-door", "venue-door"]);
});

test("the plan's PLANE_PX is the CSS's plane, and the plane is SQUARE", () => {
  // Two copies of one number, and the room breaks quietly if they disagree:
  // `PLANE_PX` sets how far a traffic dot travels along a wire, and
  // `.kt-floor-plane` sets how far the desks actually are. When the plane grew
  // 640 -> 760 on 2026-08-22, a stale constant would have left every dot 16%
  // short of its destination — moving, plausible, and wrong.
  //
  // SQUARE is a correctness constraint, not a look. The SVG floor is drawn with
  // `preserveAspectRatio="none"` over `viewBox="0 0 100 100"` while the desk
  // cards are placed as PERCENTAGES of the same box; the grid, the corridor and
  // the lamps sit under the right desks only because both axes scale alike.
  const css = readFileSync(
    new URL("../../studio-theme.css", import.meta.url), "utf8");
  const plane = css.match(/\.kt-floor-plane\s*\{[^}]*\}/);
  assert.ok(plane, "the .kt-floor-plane rule is gone from studio-theme.css");
  const w = plane![0].match(/width:\s*(\d+)px/);
  const h = plane![0].match(/height:\s*(\d+)px/);
  assert.ok(w && h, "the plane no longer declares a pixel width and height");
  assert.equal(Number(w![1]), PLANE_PX,
    "floorPlan.PLANE_PX and .kt-floor-plane disagree — the pulses will miss their desks");
  assert.equal(Number(h![1]), Number(w![1]),
    "the plane is no longer square — the SVG floor and the desk cards will disagree about where a desk is");

  const floorSrc = readFileSync(new URL("./Floor.tsx", import.meta.url), "utf8");
  assert.match(floorSrc, /preserveAspectRatio="none"/,
    "the SVG layer must cover the plane box exactly, or it letterboxes away from the furniture");
});

test("no seat is drawn twice — the exec row and the bench are disjoint", () => {
  // The failure this caught when Donna was added: BENCH_ORDER derived from
  // SEATS minus the coo, so she appeared at her exec desk AND on the bench.
  const ids = allSpots().map((s) => s.id);
  assert.equal(new Set(ids).size, ids.length, "a spot id appears twice in the room");
});

/* --------------------------------------------------- the third state ------ */
/* CEO, request 907ecc74: three finished dispatches rendered as WORKING for
   hours, because the floor drew two states where there are three. */

test("a returned dispatch is NOT lit like a working seat", () => {
  const roster = [
    { agent: "pm", activity: { status: "working" } },
    { agent: "builder", activity: { status: "awaiting_review" } },
    { agent: "quant", activity: { status: "idle" } },
  ] as unknown as Parameters<typeof litSeats>[0];
  // THE regression. A lamp says "someone is at that desk"; a returned dispatch
  // means the opposite, and drawing them alike is what hid the review queue.
  assert.deepEqual(litSeats(roster), ["pm"]);
  assert.deepEqual(awaitingReviewSeats(roster), ["builder"]);
});

test("no roster means no awaiting seats — never 'everything reviewed'", () => {
  assert.deepEqual(awaitingReviewSeats(null), []);
  assert.deepEqual(awaitingReviewSeats(undefined), []);
});

test("a row with no activity block is neither lit nor awaiting", () => {
  const roster = [{ agent: "analyst" }] as unknown as Parameters<typeof litSeats>[0];
  assert.deepEqual(litSeats(roster), []);
  assert.deepEqual(awaitingReviewSeats(roster), []);
});

test("an undetectable return is named, not hidden behind a confident WORKING", () => {
  // Measured 2026-08-21: only 8 of 23 dispatched task_ids carry a run with a
  // matching trace, so WORKING is a floor and the floor must say so.
  const roster = [
    { agent: "pm", activity: { status: "working", review_detectable: false } },
    { agent: "quant", activity: { status: "working", review_detectable: true } },
    // Idle seats have nothing to detect; `null` must not read as blind.
    { agent: "adversary", activity: { status: "idle", review_detectable: null } },
  ] as unknown as Parameters<typeof litSeats>[0];
  assert.deepEqual(reviewDetectionBlind(roster), ["pm"]);
});
