/**
 * The floor's guard rails — one test per way the room could lie.
 *
 * Run: `node --experimental-strip-types --test src/app/clark/studio/desk/floor/floorPlan.test.ts`
 *
 * The CDO spec (docs/design/CDO_AUDIT_2026-08-20.md, Deliverable B) states seven
 * acceptance criteria, each with a named falsifier. Four of them are assertions
 * about derived facts and are pinned HERE; the other three (bundle delta, theme
 * tokens, no new dependencies) are properties of the built artifact and are
 * measured on the worktree, not asserted in a unit test — stated so a reader of
 * this file does not conclude the suite covers all seven.
 *
 * The failure this file exists to make impossible: **an animated floor that
 * moves when nothing happened.** Ambient traffic on a room that claims to show
 * real traffic is the visual form of rendering an absent number as zero — it
 * reads as a busy firm and is generated by a timer.
 */

import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

import type { SpineEvent } from "@/lib/fund_api";
import { SEATS } from "../seatLib.ts";
import { faceFor } from "../faces.ts";
import {
  BENCH_ORDER,
  CAMERA_TRANSFORM,
  CHAIN,
  CORRIDOR,
  EXEC_ROW,
  FIXTURES,
  allSpots,
  benchSpots,
  corridorHasNoShortcut,
  floorEnabledFrom,
  floorPulses,
  litSeats,
  pulsesByWire,
  roomState,
  spotById,
} from "./floorPlan.ts";

/* ------------------------------------------------------------------ flag --- */

test("the floor is off unless NEXT_PUBLIC_STUDIO_FLOOR is exactly 1", () => {
  assert.equal(floorEnabledFrom(undefined), false);
  assert.equal(floorEnabledFrom(null), false);
  assert.equal(floorEnabledFrom(""), false);
  assert.equal(floorEnabledFrom("0"), false);
  // "true" is not 1. The spec names the value; a flag that accepts anything
  // truthy is a flag that turns itself on in an environment nobody checked.
  assert.equal(floorEnabledFrom("true"), false);
  assert.equal(floorEnabledFrom("1"), true);
});

test("the flag is read as a LITERAL process.env member, or the browser never sees it", () => {
  // The incident this pins (builder D5, found by screenshot): `floorEnabled`
  // originally took `env = process.env` as a parameter. Next inlines
  // NEXT_PUBLIC_* only where the member access is written out literally, so in
  // the browser the injected object was empty and the room reported itself
  // "not enabled" with the flag set. A unit test cannot see webpack, so this
  // asserts on the SOURCE: the literal read must be present and must not be
  // reachable through an injected bag.
  const src = readFileSync(
    new URL("./floorPlan.ts", import.meta.url), "utf8");
  assert.match(src, /floorEnabledFrom\(process\.env\.NEXT_PUBLIC_STUDIO_FLOOR\)/,
    "the literal member access is gone — the browser will read an empty env");
  assert.doesNotMatch(src, /=\s*process\.env\s*\)/,
    "process.env is being passed as an object again; Next will not inline it");
});

/* ------------------------------------------------- geometry = org chart ---- */

test("the exec row is the reporting line: corner office, triage, console", () => {
  assert.deepEqual(EXEC_ROW.map((s) => s.id), ["ceo", "coo", "cto"]);
  // Left to right along the back wall, and the corner office is IN the corner.
  const xs = EXEC_ROW.map((s) => s.at.x);
  assert.deepEqual([...xs].sort((a, b) => a - b), xs);
  assert.ok(EXEC_ROW[0].at.x < 25, "the corner office must sit against the wall");
});

test("exactly ONE inbox tray exists, and it is in the corner office", () => {
  // The spec's sharpest sentence: the approval queue lives there and only
  // there. A second tray anywhere on this floor would draw a second place the
  // click could live, which is the one thing the constitution says is false.
  const trays = allSpots().filter((s) => s.inboxTray);
  assert.equal(trays.length, 1);
  assert.equal(trays[0].id, "ceo");
  const triage = allSpots().filter((s) => s.triageTray);
  assert.equal(triage.length, 1);
  assert.equal(triage[0].id, "coo", "the triage tray feeds the corner office; it is not one");
});

test("the bench is in CONSTITUTION order, two rows of four, and the coo is not on it", () => {
  assert.equal(BENCH_ORDER.length, 8);
  assert.deepEqual([...BENCH_ORDER], SEATS.filter((s) => s !== "coo"));
  const spots = benchSpots();
  assert.equal(spots.length, 8);
  const rows = new Set(spots.map((s) => s.at.y));
  assert.equal(rows.size, 2, "two rows");
  for (const y of rows) {
    assert.equal(spots.filter((s) => s.at.y === y).length, 4, "of four");
  }
  // Reading order within a row is constitution order, not alphabetical and not
  // whatever /fund/desk returned. The live roster today hands back builder
  // before riskofficer; the floor must not inherit that.
  const first = spots.filter((s) => s.at.y === spots[0].at.y);
  assert.deepEqual(first.map((s) => s.id), ["mechanism", "analyst", "pm", "quant"]);
});

test("every desk's accessible sentence comes from faces.ts, verbatim", () => {
  // Criterion 5. A hand-written second copy of "what the adversary does" is a
  // second thing to drift, and the drift would be invisible: both sentences
  // read fine, only one is the registry's.
  for (const s of benchSpots()) {
    const f = faceFor(s.id);
    assert.ok(f, `no face for ${s.id}`);
    assert.equal(s.says, f!.role);
  }
});

test("Abhishek's wing is a DOOR with no interior, and it opens his existing page", () => {
  const door = spotById("thesis-door");
  assert.ok(door);
  assert.equal(door!.kind, "door");
  assert.equal(door!.href, "/clark/studio/thesis");
  assert.match(door!.label, /observe only/);
  // Nothing else in the room may point into the thesis surface — the floor
  // draws a door, never a room.
  const inside = allSpots().filter(
    (s) => s.id !== "thesis-door" && (s.href || "").includes("/thesis"),
  );
  assert.deepEqual(inside, []);
});

test("the auto-policy is a caged MACHINE by the venue door, never a colleague", () => {
  const cage = spotById("autopolicy-cage");
  const venue = spotById("venue-door");
  assert.ok(cage && venue);
  assert.equal(cage!.kind, "machine");
  assert.equal(cage!.href, null, "the cage is not a door — nothing on this floor opens it");
  // "beside the venue door" is a measurable claim, so it is measured.
  const d = Math.hypot(cage!.at.x - venue!.at.x, cage!.at.y - venue!.at.y);
  assert.ok(d < 20, `the cage is ${d.toFixed(1)} units from the venue door — not beside it`);
  // Neither fixture may light: a machine is not "working".
  assert.ok(!cage!.lampable && !venue!.lampable);
});

test("no fixture is lampable, and every bench seat is", () => {
  for (const f of FIXTURES) {
    assert.ok(!f.lampable, `${f.id} is a fixture and must never light as a working seat`);
  }
  for (const s of benchSpots()) assert.ok(s.lampable);
});

/* ----------------------------------------------- the chain as a corridor --- */

test("the corridor walks the constitution's chain and offers NO shortcut", () => {
  assert.deepEqual([...CHAIN], ["mechanism", "adversary", "cto", "machine-room", "ceo"]);
  assert.ok(corridorHasNoShortcut(),
    "the aisle reaches a station out of chain order, or skips one — a shortcut " +
    "aisle draws a path the constitution does not have");
  // ONE polyline: every station lies ON it, and it is a single unbranched run
  // of points (no point repeats, which is what a branch would require).
  const seen = new Set(CORRIDOR.map((p) => `${p.x},${p.y}`));
  assert.equal(seen.size, CORRIDOR.length, "a repeated waypoint is a branch");
  for (const id of CHAIN) {
    const s = spotById(id)!;
    assert.ok(CORRIDOR.some((p) => p.x === s.at.x && p.y === s.at.y),
      `${id} is a chain station but the aisle does not reach it`);
  }
});

test("every corridor segment is an aisle, not a diagonal short-cut across desks", () => {
  // Two consecutive waypoints may differ on at most one axis OR be the single
  // dog-leg into the machine room. A free diagonal would let a future edit draw
  // mechanism→ceo as one straight line and still pass the ordering test above.
  let diagonals = 0;
  for (let i = 1; i < CORRIDOR.length; i++) {
    const a = CORRIDOR[i - 1], b = CORRIDOR[i];
    if (a.x !== b.x && a.y !== b.y) diagonals += 1;
  }
  assert.ok(diagonals <= 2, `${diagonals} diagonal aisle segments — the room is being cut across`);
});

/* ---------------------------------------------------------- the room state -- */

test("a dead spine is UNLIT, and is not the same fact as a quiet room", () => {
  // Criterion 3. Either read failing darkens the room.
  assert.equal(roomState({ deskReadable: false, monitorReadable: true, halted: false }), "dead");
  assert.equal(roomState({ deskReadable: true, monitorReadable: false, halted: false }), "dead");
  assert.equal(roomState({ deskReadable: true, monitorReadable: true, halted: false }), "lit");
  assert.equal(roomState({ deskReadable: true, monitorReadable: true, halted: true }), "halted");
  // A monitor that did not report `halted` is not a monitor reporting calm —
  // but it IS readable, so the room stays lit and the strip stays dark. The
  // RiskBar owns the sentence about an unreachable monitor; the floor must not
  // invent a second, softer one.
  assert.equal(roomState({ deskReadable: true, monitorReadable: true, halted: null }), "lit");
});

test("no roster means NO lamps — never 'everyone idle'", () => {
  assert.deepEqual(litSeats(null), []);
  assert.deepEqual(litSeats(undefined), []);
  const roster = [
    { agent: "pm", activity: { status: "working" } },
    { agent: "quant", activity: { status: "idle" } },
    // A roster row with no activity block at all: absent, so unlit.
    { agent: "analyst" },
  ] as unknown as Parameters<typeof litSeats>[0];
  assert.deepEqual(litSeats(roster), ["pm"]);
});

/* ------------------------------------------------------------- the pulses -- */

const ev = (
  type: string, id: string, ts: string, actor: string,
  payload: Record<string, unknown>,
): SpineEvent => ({
  event_id: id, type, ts, actor, payload,
} as unknown as SpineEvent);

test("pulse count equals desk-event count, and every pulse carries a real event id", () => {
  // Criterion 4, the replay test. Its falsifier: a pulse whose event_id is not
  // in the source log, or a count that exceeds the events supplied.
  const events = [
    ev("DeskRequested", "e1", "2026-08-21T10:00:00Z", "ceo",
       { serves: "pm", subject: "review the sleeve" }),
    ev("DeskDispatched", "e2", "2026-08-21T10:01:00Z", "cto",
       { seat: "pm", task_id: "r1", task: "sleeve v2" }),
    ev("DeskRequestResolved", "e3", "2026-08-21T10:02:00Z", "cto",
       { request_id: "r1", resolution: "docs/pm/X.md" }),
    ev("DeskRecommendationDecided", "e4", "2026-08-21T10:03:00Z", "ceo",
       { seat: "pm", status: "accepted", text: "trim GLD" }),
    // Not desk traffic. Must draw nothing: the room shows the DESK's wire.
    ev("OrderApproved", "e5", "2026-08-21T10:04:00Z", "ceo", { approver: "ceo" }),
    ev("NavStruck", "e6", "2026-08-21T10:05:00Z", "system", { total_nav_usd: 2011.81 }),
  ];
  const { pulses, total } = floorPulses(events, 50);
  assert.equal(total, 4, "only the four desk event types are traffic");
  assert.equal(pulses.length, 4, "one pulse per desk event, no more and no fewer");
  const ids = new Set(events.map((e) => e.event_id));
  for (const p of pulses) {
    assert.ok(ids.has(p.eventId), `pulse ${p.eventId} has no event behind it`);
  }
  assert.equal(new Set(pulses.map((p) => p.eventId)).size, 4, "no event drawn twice");
});

test("an empty log draws an empty room — there is no ambient traffic branch", () => {
  // The single most important assertion in this file. If the floor ever grows a
  // decorative animation, this is where it shows up.
  assert.deepEqual(floorPulses([], 50), { pulses: [], total: 0 });
  assert.deepEqual(floorPulses(null, 50), { pulses: [], total: 0 });
  assert.deepEqual(floorPulses(undefined, 50), { pulses: [], total: 0 });
});

test("the drawn window is clipped newest-first and the total is reported, never implied", () => {
  const events = Array.from({ length: 30 }, (_, i) =>
    ev("DeskDispatched", `e${i}`, `2026-08-21T10:${String(i).padStart(2, "0")}:00Z`,
       "cto", { seat: "pm", task_id: `r${i}`, task: `t${i}` }));
  const { pulses, total } = floorPulses(events, 5);
  assert.equal(total, 30, "the total counts every desk event read, not the drawn window");
  assert.equal(pulses.length, 5);
  assert.deepEqual(pulses.map((p) => p.eventId), ["e29", "e28", "e27", "e26", "e25"]);
});

test("a delivery names its sender by matching the dispatch, and says so when it cannot", () => {
  // DeskRequestResolved carries {request_id, resolution, actor, trace_id} and
  // NO seat — verified on the live log 2026-08-21. Guessing a seat here would
  // draw an artifact arriving from a desk that never sent it.
  const matched = floorPulses([
    ev("DeskDispatched", "d1", "2026-08-21T09:00:00Z", "cto",
       { seat: "validator", task_id: "req-1", task: "audit" }),
    ev("DeskRequestResolved", "r1", "2026-08-21T09:30:00Z", "cto",
       { request_id: "req-1", resolution: "docs/AUDIT.md" }),
  ], 50).pulses.find((p) => p.eventId === "r1")!;
  assert.equal(matched.fromId, "validator");
  assert.equal(matched.toId, "cto");
  assert.equal(matched.verb, "delivered");
  assert.equal(matched.offFloor, null);

  const orphan = floorPulses([
    ev("DeskRequestResolved", "r2", "2026-08-21T09:30:00Z", "cto",
       { request_id: "req-missing", resolution: "docs/X.md" }),
  ], 50).pulses[0];
  assert.equal(orphan.fromId, null);
  assert.match(orphan.offFloor!, /outside the events read/);
  // It still counts. An unattributable delivery is a fact about the record.
  assert.equal(floorPulses([
    ev("DeskRequestResolved", "r2", "2026-08-21T09:30:00Z", "cto",
       { request_id: "req-missing", resolution: "docs/X.md" }),
  ], 50).total, 1);
});

test("a seat with no desk on this floor is NAMED, not dropped and not drawn as someone else", () => {
  // `cdo-trial` is a real seat on the live log with no chair in this room.
  const p = floorPulses([
    ev("DeskRecommendationDecided", "x1", "2026-08-21T11:00:00Z", "ceo",
       { seat: "cdo-trial", status: "accepted", text: "the floor spec" }),
  ], 50).pulses[0];
  assert.equal(p.fromId, "ceo");
  assert.equal(p.toId, null);
  assert.match(p.offFloor!, /cdo-trial/);
  assert.match(p.offFloor!, /no desk on this floor/);
});

test("wires group pulses without losing any — reduced motion must lose no information", () => {
  // Criterion 2's information-parity half: under the media query the moving dot
  // is replaced by a dashed aisle plus a COUNT CHIP, and the count comes from
  // here. If grouping ever dropped a pulse, the chip would under-report and the
  // reduced-motion reader would see a calmer firm than the animated one.
  const events = [
    ev("DeskDispatched", "a", "2026-08-21T10:00:00Z", "cto", { seat: "pm", task_id: "1" }),
    ev("DeskDispatched", "b", "2026-08-21T10:01:00Z", "cto", { seat: "pm", task_id: "2" }),
    ev("DeskDispatched", "c", "2026-08-21T10:02:00Z", "cto", { seat: "quant", task_id: "3" }),
    ev("DeskRecommendationDecided", "d", "2026-08-21T10:03:00Z", "ceo",
       { seat: "cdo-trial", status: "accepted" }),
  ];
  const { pulses } = floorPulses(events, 50);
  const wires = pulsesByWire(pulses);
  const onWires = wires.reduce((n, w) => n + w.pulses.length, 0);
  const offFloor = pulses.filter((p) => !p.fromId || !p.toId).length;
  assert.equal(onWires + offFloor, pulses.length,
    "every pulse is either on a wire or explicitly off-floor — none may vanish");
  const toPm = wires.find((w) => w.key === "cto>pm")!;
  assert.equal(toPm.pulses.length, 2);
});

/* ---------------------------------------------------------------- camera --- */

test("the camera is fixed, orthographic and dimetric — no perspective, ever", () => {
  // The spec forbids free cameras and lighting; a perspective camera would also
  // make the BACK of the room (where the approvals are) the smallest thing on
  // screen. One rotate pair, no perspective(), no scale.
  assert.ok(!CAMERA_TRANSFORM.includes("perspective"));
  assert.ok(!CAMERA_TRANSFORM.includes("scale"));
  assert.equal((CAMERA_TRANSFORM.match(/rotate/g) || []).length, 2);
});
