"""24/7 Autonomous R&D Strategy Department Runner for ClarkHarness.

Continuously sweeps strategy parameters across target symbols, executes backtests on the spine,
and records candidate strategies with high Sharpe ratios (>0.5) and positive returns into the fund store.
"""

import asyncio
import logging
import os
from datetime import datetime, timezone
import httpx

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("rd_strategy_runner")

HARNESS_URL = os.getenv("CLARK_HARNESS_URL", "http://127.0.0.1:8090").rstrip("/") + "/api/v1/fund"

TARGET_SYMBOLS = ["AAPL", "NVDA", "MSFT", "SPY", "BTC", "ETH", "SOL"]
STRATEGIES_TO_SWEEP = [
    {"name": "sma", "fast": 10, "slow": 50},
    {"name": "rsi", "rsi_period": 14, "rsi_low": 30, "rsi_high": 70},
    {"name": "macd", "fast": 12, "slow": 26, "signal": 9},
]


async def run_rd_cycle():
    logger.info("Starting 24/7 R&D Strategy Optimization Sweep...")
    async with httpx.AsyncClient(timeout=30) as client:
        try:
            res = await client.get(f"{HARNESS_URL}/strategies")
            if res.status_code != 200:
                logger.error("Harness returned status %d", res.status_code)
                return
            strats = res.json().get("strategies", [])
            strat_id = strats[0]["strategy_id"] if strats else None
        except Exception as e:
            logger.error("Could not connect to harness at %s: %s", HARNESS_URL, e)
            return

        if not strat_id:
            # Create a scratchpad strategy
            reg = await client.post(f"{HARNESS_URL}/strategies", json={"name": "Scratchpad", "actor": "rd_runner_agent"})
            if reg.status_code == 200:
                strat_id = reg.json().get("strategy_id")

        if not strat_id:
            logger.error("Could not obtain a strategy ID for backtest runner.")
            return

        candidates_found = 0
        for symbol in TARGET_SYMBOLS:
            for strat_spec in STRATEGIES_TO_SWEEP:
                strat_type = strat_spec["name"]
                try:
                    payload = {
                        "symbol": symbol,
                        "strategy": strat_type,
                        "lookback_days": 180,
                        "actor": "rd_runner_agent",
                    }
                    if "fast" in strat_spec: payload["fast"] = strat_spec["fast"]
                    if "slow" in strat_spec: payload["slow"] = strat_spec["slow"]

                    r = await client.post(f"{HARNESS_URL}/strategies/{strat_id}/backtest/by_symbol", json=payload)
                    if r.status_code == 200:
                        data = r.json()
                        result = data.get("result", {})
                        sharpe = result.get("sharpe", 0.0)
                        ret = result.get("total_return", 0.0)

                        logger.info("Sweep result for %s (%s): Return=%.2f%%, Sharpe=%.2f", symbol, strat_type, ret, sharpe)

                        if sharpe > 0.3 and ret > 0.0:
                            candidates_found += 1
                            strat_name = f"R&D Auto-{symbol}-{strat_type.upper()}"
                            reg_res = await client.post(
                                f"{HARNESS_URL}/strategies",
                                json={
                                    "name": strat_name,
                                    "definition": f"Auto-generated by R&D runner on {datetime.now(timezone.utc).isoformat()}",
                                    "parent_id": strat_id,
                                    "actor": "rd_runner_agent",
                                },
                            )
                            if reg_res.status_code == 200:
                                logger.info("Successfully registered candidate strategy proposal: %s", strat_name)
                except Exception as e:
                    logger.warning("Sweep iteration failed for %s (%s): %s", symbol, strat_type, e)

        logger.info("R&D Cycle Complete. Candidate proposals registered: %d", candidates_found)


if __name__ == "__main__":
    asyncio.run(run_rd_cycle())
