/**
 * GENERATE `contract/desk_card_contract.v2.json` — the TICKET card's contract.
 *
 * WHY GENERATED AND NOT TYPED. v1's own test says it: *"generated ... never
 * typed by hand, so it cannot encode a wish."* A contract a human types is a
 * statement of intent; a contract a program emits from the code under test is
 * a statement of behaviour, and only the second one can fail.
 *
 * **AND THIS ONE GOES ONE STEP FURTHER THAN v1.** v1 is generated in
 * ClarkHarness and this repo's test asserts the fixture is internally
 * CONSISTENT WITH ITSELF — totals derived rather than retyped, a digest pinned.
 * That is the strongest thing available when the producing code lives across a
 * repo boundary. The ticket card's producing code lives HERE, in
 * `studio/desk/ticketCard.ts`, so v2's test drives the real function over every
 * case and compares. **A contract case here is an acceptance test, not a
 * fixture.**
 *
 * WHAT IS OWED AND IS NOT DONE (stated rather than quietly skipped): the
 * ClarkHarness copy. v1 is checked in to both repos byte-identical and
 * regenerated by `scripts/gen_desk_contract.py` there. **This dispatch is
 * KryptonPay-only and that repo is under review, so the ClarkHarness-side copy
 * of v2 and the generator entry that would emit it are OWED, not written.**
 * Until they exist, v2 binds one repo — which is honest, and less than v1.
 *
 * USAGE
 *   node scripts/contract/gen_ticket_card_contract.mjs          # write
 *   node scripts/contract/gen_ticket_card_contract.mjs --check  # verify only
 *
 * `--check` exits 1 if the checked-in file differs, so CI or a human can tell
 * a stale contract from a current one without reading JSON.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../../contract/desk_card_contract.v2.json");

/** A ticket row with the fold's own defaults. The cases override from here, so
 *  a case says only what it is ABOUT. */
function row(over) {
  return {
    ticket_id: over.ticket_id ?? "t-0",
    type: over.type ?? "recommendation",
    state: over.state ?? "filed",
    subject: over.subject ?? "Decide this.",
    filed_for: "builder",
    filed_by: "cto",
    filed_at: "2026-08-24T00:00:00+00:00",
    trace_id: null,
    parent_id: null,
    source: "deskstore.recommendations",
    transitions: [],
    refused_transitions: [],
    terminal: over.terminal ?? false,
    next_actor: over.next_actor ?? "ceo",
    next_actor_basis: "explicit",
    next_actor_why: over.next_actor_why ?? "the row states its next actor is the ceo",
    age_hours: 40,
    age_basis: "event_timestamps",
    age_in_state_hours: over.age_in_state_hours === undefined
      ? 40 : over.age_in_state_hours,
    age_in_state_basis: over.age_in_state_basis ?? "event_timestamps",
    decided: over.decided ?? false,
    decision_count: over.decision_count ?? 0,
    decided_state: over.decided_state ?? null,
    decided_at: over.decided_at ?? null,
    decided_by: over.decided_by ?? null,
    canonical_ticket_id: null,
    decision_basis: "transitions",
    ...over,
  };
}

const TERMINALS = ["done", "declined", "superseded", "merged", "expired"];

const cases = [
  {
    name: "UNDECIDED AND YOURS — the only shape with a decision control",
    why: "the baseline. 35 of the 57 rows the fold routes to the CEO on the "
      + "live record. Every other case below is defined by how it must NOT "
      + "look like this one.",
    row: row({ ticket_id: "undecided" }),
    expect: {
      controls: "decide", countedAsAwaiting: true, awaitingActor: "ceo",
      terminal: false, lamp: "idle", citationOwed: false,
    },
  },
  {
    name: "DECIDED AND YOURS — execution owed, and NOT another decision",
    why: "22 of the 57 on the live record, and the v1 contract's sharpest "
      + "case carried onto the highway: he accepted it, the write landed, the "
      + "page refetched, and the row came back with an Accept button — a "
      + "successful click and a dead click were the same picture. `decided` "
      + "survives the move out of `filed`, so this is READ, never inferred "
      + "from the state name.",
    row: row({
      ticket_id: "execution-yours", state: "accepted", decided: true,
      decision_count: 1, decided_state: "accepted", decided_by: "ceo",
      decided_at: "2026-08-24T09:12:00+00:00",
    }),
    expect: {
      controls: "execute", countedAsAwaiting: true, awaitingActor: "ceo",
      terminal: false, lamp: "idle", citationOwed: false,
    },
  },
  {
    name: "DECIDED, AND THE CHAIR OWES THE EXECUTION",
    why: "the ordinary decided row. Counted as awaiting the CHAIR — which is "
      + "the case that proves `countedAsAwaiting` and `controls` are separate "
      + "questions: no control here, and somebody is still waiting. One flag "
      + "answering both is D39's P-2, which silently removed the CEO's own "
      + "approve button.",
    row: row({
      ticket_id: "chair-executes", state: "accepted", decided: true,
      decision_count: 1, decided_state: "accepted", decided_by: "ceo",
      next_actor: "chair", next_actor_why: "the chair stages this one",
    }),
    expect: {
      controls: "none", countedAsAwaiting: true, awaitingActor: "chair",
      terminal: false, lamp: "idle", citationOwed: false,
    },
  },
  {
    name: "`nobody` — filed for the record, open, and finished",
    why: "D42's kill, preserved unchanged on the highway. The row's state is "
      + "working and nothing is owed on it; the spine says so and this reads "
      + "it rather than guessing. NOT counted as awaiting anyone.",
    row: row({
      ticket_id: "record-row", next_actor: "nobody",
      next_actor_why: "the row states its next actor is the nobody",
    }),
    expect: {
      controls: "none", countedAsAwaiting: false, awaitingActor: null,
      terminal: false, lamp: "idle", citationOwed: false,
    },
  },
  ...TERMINALS.map((state) => ({
    name: `TERMINAL \`${state}\` — no control, counted as awaiting nobody`,
    why: "the generalisation of D42 from one field value to the lifecycle, "
      + "and the CEO's second requirement of 2026-08-26 verbatim: \"no stale "
      + "cards are there\". The row is routed to the CEO on purpose here: a "
      + "terminal check that only fired when the actor was already `nobody` "
      + "would pass every other case in this file and still ship the defect.",
    row: row({
      ticket_id: `terminal-${state}`, state, terminal: true,
      next_actor: "ceo", citation: "seq 1281",
    }),
    expect: {
      controls: "none", countedAsAwaiting: false, awaitingActor: null,
      terminal: true, lamp: "record", citationOwed: false,
    },
  })),
  {
    name: "CLOSED WITH NO CITATION — a bookkeeping gap, not a completed close",
    why: "the design makes a citation mandatory for `done` (\"no citation, no "
      + "close\"). A legacy fold usually cannot supply one, and rendering that "
      + "as a clean close would launder the gap into a completion.",
    row: row({
      ticket_id: "closed-uncited", state: "done", terminal: true,
      next_actor: "nobody",
    }),
    expect: {
      controls: "none", countedAsAwaiting: false, awaitingActor: null,
      terminal: true, lamp: "record", citationOwed: true,
    },
  },
  {
    name: "A DECLINED TICKET WITH NO CITATION IS NOT A GAP",
    why: "only `done` claims the work happened. A decline needs a reason, "
      + "which is a different field and a different rule — flagging it here "
      + "would put a repair target on a correctly closed row.",
    row: row({
      ticket_id: "declined-uncited", state: "declined", terminal: true,
      next_actor: "nobody", reason: "the CEO said no",
    }),
    expect: {
      controls: "none", countedAsAwaiting: false, awaitingActor: null,
      terminal: true, lamp: "record", citationOwed: false,
    },
  },
  {
    name: "THE TERMINAL FLAG IS ABSENT — the state list is the fallback",
    why: "a payload predating the `terminal` field must not default to \"still "
      + "open\", because that is the direction that puts a button on a closed "
      + "row. The flag wins where it exists; the list catches where it does "
      + "not.",
    row: (() => { const r = row({ ticket_id: "no-flag", state: "merged" });
                  delete r.terminal; return r; })(),
    expect: {
      controls: "none", countedAsAwaiting: false, awaitingActor: null,
      terminal: true, lamp: "record", citationOwed: false,
    },
  },
  {
    name: "`returned` — the constitution's missing middle state, finally lit",
    why: "\"A dispatch has three states and the floor currently renders two.\" "
      + "An unreviewed return has been indistinguishable from a seat still "
      + "thinking; this is the lamp that separates them. Live count today: 0 "
      + "— the door exists and nothing has used it.",
    row: row({
      ticket_id: "returned-row", type: "dispatch", state: "returned",
      next_actor: "chair", next_actor_why: "the chair owes a review",
    }),
    expect: {
      controls: "none", countedAsAwaiting: true, awaitingActor: "chair",
      terminal: false, lamp: "awaiting-review", citationOwed: false,
    },
  },
  {
    name: "`in_flight` — a seat is running",
    why: "the working lamp. Nine live rows.",
    row: row({
      ticket_id: "in-flight-row", type: "dispatch", state: "in_flight",
      next_actor: "chair", next_actor_why: "the chair sees it back",
    }),
    expect: {
      controls: "none", countedAsAwaiting: true, awaitingActor: "chair",
      terminal: false, lamp: "working", citationOwed: false,
    },
  },
  {
    name: "DICT PAYLOAD — renders its content, never a tidy blank",
    why: "seven of the 713 live tickets store a Python repr where a sentence "
      + "belongs. The row IS broken and the reader must see that it is; "
      + "hiding it would make a bookkeeping defect invisible on the surface "
      + "built to end them.",
    row: row({
      ticket_id: "repr-subject",
      subject: "{'id': 'E20-1', 'title': 'Entry 20 premia pass'}",
    }),
    expect: {
      controls: "decide", countedAsAwaiting: true, awaitingActor: "ceo",
      terminal: false, lamp: "idle", citationOwed: false,
      titleLooksUnreadable: true, titleAbsent: false,
    },
  },
  {
    name: "AN OBJECT SUBJECT NEVER RENDERS AS `[object Object]`",
    why: "`subject` is typed `unknown` because the fold copies whatever the "
      + "source event carried. `String({})` is a tidy blank wearing a value.",
    row: row({ ticket_id: "object-subject", subject: { title: "a real title" } }),
    expect: {
      controls: "decide", countedAsAwaiting: true, awaitingActor: "ceo",
      terminal: false, lamp: "idle", citationOwed: false,
      titleLooksUnreadable: true, titleAbsent: false,
    },
  },
  {
    name: "A BLANK SUBJECT IS ABSENT, and absent is not unreadable",
    why: "nothing was stored, rather than something unreadable was. Two "
      + "different facts and two different sentences.",
    row: row({ ticket_id: "blank-subject", subject: "   " }),
    expect: {
      controls: "decide", countedAsAwaiting: true, awaitingActor: "ceo",
      terminal: false, lamp: "idle", citationOwed: false,
      titleLooksUnreadable: false, titleAbsent: true,
    },
  },
  {
    name: "AN UNREADABLE AGE RENDERS UNKNOWN, NEVER 0h",
    why: "the fund's oldest rule at the level of one card. The fold publishes "
      + "`age_in_state_basis: \"unknown\"` when it could not read the "
      + "instants, and a card that printed 0h would be inventing a "
      + "measurement.",
    row: row({
      ticket_id: "unreadable-age", age_in_state_hours: null,
      age_in_state_basis: "unknown",
    }),
    expect: {
      controls: "decide", countedAsAwaiting: true, awaitingActor: "ceo",
      terminal: false, lamp: "idle", citationOwed: false,
      ageKnown: false, ageInStateHours: null,
    },
  },
];

/** Totals DERIVED from the cases, never retyped — a hand-written total is a
 *  second source of truth that silently stops matching. */
const expect_totals = {
  cases: cases.length,
  with_a_decision_control: cases.filter(
    (c) => c.expect.controls === "decide").length,
  with_an_execution_control: cases.filter(
    (c) => c.expect.controls === "execute").length,
  with_no_control: cases.filter((c) => c.expect.controls === "none").length,
  terminal: cases.filter((c) => c.expect.terminal).length,
  counted_as_awaiting: cases.filter((c) => c.expect.countedAsAwaiting).length,
  /** THE ONE NUMBER THE WHOLE FILE EXISTS FOR. */
  terminal_rows_offering_a_control: cases.filter(
    (c) => c.expect.terminal && c.expect.controls !== "none").length,
};

const body = {
  contract: "desk_card",
  version: 2,
  supersedes: null,
  covers: "what a TICKET row renders as — the control it offers, whether "
    + "anybody is counted as waiting on it, and what it says where a control "
    + "is absent. ADDITIVE TO v1, which is untouched: v1 covers desk "
    + "recommendation/request rows and their nine states; v2 covers the "
    + "highway's ten lifecycle states. Neither binds a count; the stage "
    + "contract binds the count.",
  rules_version: "ticket card v2 (2026-08-26)",
  producing_module: "src/app/clark/studio/desk/ticketCard.ts::ticketCardState",
  clarkharness_copy: "OWED. v1 is checked in to both repos byte-identical and "
    + "regenerated by ClarkHarness's scripts/gen_desk_contract.py. This "
    + "dispatch is KryptonPay-only, so the ClarkHarness copy of v2 and its "
    + "generator entry do not exist yet and v2 binds ONE repo until they do.",
  lifecycle_working: ["filed", "approved", "in_flight", "returned", "accepted"],
  lifecycle_terminal: TERMINALS,
  controls: ["decide", "execute", "none"],
  lamps: ["working", "awaiting-review", "idle", "record"],
  invariants: [
    "a terminal ticket offers NO control, under every next_actor",
    "a terminal ticket is counted as awaiting NOBODY",
    "`controls` and `countedAsAwaiting` are computed independently — a row "
      + "with no control may still have somebody waiting on it",
    "`controlsWhy` is never empty, so a missing control is never a blank",
    "an unreadable age is null with ageKnown false, never 0",
    "a `done` ticket with no citation is flagged as a bookkeeping gap",
  ],
  cases,
  expect_totals,
};

const json = JSON.stringify(body, null, 1);
const digest = createHash("sha256").update(json).digest("hex");
const withDigest = JSON.stringify({ ...body, digest }, null, 1);

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch { /* absent */ }
  if (current !== withDigest) {
    console.error("STALE: contract/desk_card_contract.v2.json differs from "
      + "what this generator emits. Run it without --check and READ the diff "
      + "before updating the digest pinned in the test.");
    process.exit(1);
  }
  console.log(`current — ${cases.length} case(s), digest ${digest.slice(0, 12)}`);
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, withDigest);
  console.log(`wrote ${OUT}\n${cases.length} case(s); digest ${digest}`);
}
